.\" This manpage is copyright (C) 1996 Michael Shields <shields@crosslink.net>.
.\" 
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with dpkg; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.TH deb\-shlibs 5 "2007-03-08" "Debian Project" "dpkg utilities"
.SH NAME
deb\-shlibs \- Debian shared library information file
.
.SH SYNOPSIS
shlibs
.
.SH DESCRIPTION
The format for a shared library dependency information entry in these
files is (see the Debian Policy Manual for details):
.PP
<library name>        <version/soname>        <dependencies>
.
.SH SEE ALSO
.BR dpkg\-shlibdeps (1).
