.TH deb\-split 5 "2011-04-15" "Debian Project" "Debian"
.SH NAME
deb\-split \- Debian multi-part binary package format
.SH SYNOPSIS
.IB filename .deb
.SH DESCRIPTION
The multi-part \fB.deb\fP format is used to split big packages into smaller
pieces to ease transport in small media.
.SH FORMAT
The file is an \fBar\fP archive with a magic value of \fB!<arch>\fP.
The file names might contain a trailing slash (since dpkg 1.15.6).
.PP
The first member is named \fBdebian\-split\fP and contains a series
of lines, separated by newlines. Currently seven lines are present:
.IP \(bu 4
The format version number, \fB2.1\fP at the time this manual page was
written.
.IP \(bu
The package name.
.IP \(bu
The package version.
.IP \(bu
The md5sum of the package.
.IP \(bu
The total size of the package.
.IP \(bu
The maximum part size.
.IP \(bu
The current part number, followed by a slash and the total amount of
parts (as in \(oq1/10\(cq).
.PP
Programs which read multi-part archives should be prepared for additional
lines to be present, and should ignore these if this is the case.
.PP
If the version number has changed, an incompatible change has been made
and the program should stop. If it has not, then the program should
be able to safely continue, unless it encounters an unexpected member
in the archive (except at the end), as described below.
.PP
The second, last required member is named \fBdata.\fPN, where N denotes
the part number. It contains the raw part data.
.PP
These members must occur in this exact order. Current implementations
should ignore any additional members after \fBdata.\fPN.
Further members may be defined in the future, and (if possible) will be
placed after these two.
.SH SEE ALSO
.BR deb (5),
.BR dpkg\-split (1).
