.TH dpkg\-statoverride 8 "2009-06-26" "Debian project" "dpkg utilities"
.SH NAME
dpkg\-statoverride \- override ownership and mode of files
.
.SH SYNOPSIS
.B dpkg\-statoverride
.RI [ options ]
.I command
.
.SH DESCRIPTION
`\fBstat overrides\fR' are a way to tell
.BR dpkg (1)
to use a different owner
or mode for a file when a package is installed. (note: I use the word
`file' here, but in reality this can be any filesystem object that dpkg
handles, including directories, devices, etc.). This can be used to
force programs that are normally setuid to be install without a setuid
flag, or only executable by a certain group.
.P
\fBdpkg\-statoverride\fR is a utility to manage the list of stat
overrides. It has three basic functions: adding, removing and listing
overrides.
.
.SH COMMANDS
.TP
.BI \-\-add " user group mode file"
Add an override for \fIfile\fP. \fIfile\fP does not need to exist
when this command is used; the override will be stored and used later.
Users and groups can be specified by their name (for example \fBroot\fR
or \fBnobody\fR), or by their number by prepending the number with a
`\fB#\fR' (for example \fB#0\fR or \fB#65534\fR). The \fImode\fR needs
to be specified in octal.

If \-\-update is specified and \fIfile\fP exists, it is immediately
set to the new owner and mode.
.TP
.BI \-\-remove " file"
Remove an override for \fIfile\fP, the status of \fIfile\fP is left
unchanged by this command.
.TP
.BR \-\-list " [\fIglob-pattern\fP]"
List all overrides. If a glob pattern is specified restrict the output
to overrides which match the glob. If there are no overrides or none
match the glob \fBdpkg\-statoverride\fR will exit with an exitcode of 1.
.TP
.B \-\-help
Show the usage message and exit.
.TP
.B \-\-version
Show the version and exit.
.
.SH OPTIONS
.TP
.BI \-\-admindir " directory"
Change the \fIdirectory\fP of the dpkg database where the statoverride file is
also stored. Defaults to \fI/var/lib/dpkg\fP.
.TP
.B \-\-force
Force an action, even if a sanity check would otherwise prohibit it.
This is necessary to override an existing override.
.TP
.B \-\-update
Immediately try to change the file to the new owner and mode if it
exists.
.TP
.B \-\-quiet
Be less verbose about what we do.
.
.SH ENVIRONMENT
.TP
.B DPKG_ADMINDIR
If set and the \fB\-\-admindir\fP option has not been specified, it will
be used as the dpkg data directory.
.
.SH FILES
.TP
.I /var/lib/dpkg/statoverride
File which contains the current list of stat overrides of the system. It
is located in the dpkg administration directory, along with other files
important to dpkg, such as `status' or `available'.
.br
Note: \fBdpkg\-statoverride\fP preserves the old copy of this file, with
extension "\-old", before replacing it with the new one.
.
.SH SEE ALSO
.BR dpkg (1).
.
.SH AUTHOR
Copyright \(co 2000 Wichert Akkerman
.sp
This is free software; see the GNU General Public Licence version 2 or
later for copying conditions. There is NO WARRANTY.
