.TH dpkg.cfg 5 "2009-09-05" "Debian Project" "dpkg suite"
.SH NAME
dpkg.cfg \- dpkg configuration file
.
.SH DESCRIPTION
This file contains default options for dpkg. Each line contains a
single option which is exactly the same as a normal command line
option for dpkg except for the leading dashes which are not used
here. Quotes surrounding option values are stripped. Comments are
allowed by starting a line with a hash sign ("\fB#\fR").
.
.SH FILES
.I /etc/dpkg/dpkg.cfg.d/[0-9a-zA-Z_-]*
.br
.I /etc/dpkg/dpkg.cfg
.br
.I ~/.dpkg.cfg
.
.SH AUTHOR
See \fI/usr/share/doc/dpkg/THANKS\fP for the list of people who have
contributed to \fBdpkg\fP.
.
.SH SEE ALSO
.BR dpkg (1).
