.\" dpkg manual page - dpkg.cfg(5)
.\"
.\" Copyright © 2002 Wichert Akkerman <wakkerma@debian.org>
.\" Copyright © 2009 Guillem Jover <guillem@debian.org>
.\"
.\" This is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <https://www.gnu.org/licenses/>.
.
.TH dpkg.cfg 5 "2009-09-05" "Debian Project" "dpkg suite"
.SH NAME
dpkg.cfg \- dpkg configuration file
.
.SH DESCRIPTION
This file contains default options for dpkg. Each line contains a
single option which is exactly the same as a normal command line
option for dpkg except for the leading hyphens which are not used
here. Quotes surrounding option values are stripped. Comments are
allowed by starting a line with a hash sign (\(oq\fB#\fR\(cq).
.
.SH FILES
.I /etc/dpkg/dpkg.cfg.d/[0-9a-zA-Z_-]*
.br
.I /etc/dpkg/dpkg.cfg
.br
.I ~/.dpkg.cfg
.
.SH AUTHOR
See \fI/usr/share/doc/dpkg/THANKS\fP for the list of people who have
contributed to \fBdpkg\fP.
.
.SH SEE ALSO
.BR dpkg (1).
