# dpkg manual page - dpkg-realpath(1)
#
# Copyright © 2020 Guillem Jover <guillem@debian.org>
#
# This is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

=encoding utf8

=head1 NAME

dpkg-realpath - print the resolved pathname

=head1 SYNOPSIS

B<dpkg-realpath> [I<option>...] I<pathname>

=head1 DESCRIPTION

B<dpkg-realpath> is a tool to resolve a pathname.

=head1 OPTIONS

=over

=item B<--instdir> I<directory>

Set the installation directory, which refers to the directory where
packages get installed. Defaults to «I</>».

=item B<--root> I<directory>

Set the root directory to B<directory>, which sets the installation
directory to «I<directory>».

=item B<-?>, B<--help>

Show the usage message and exit.

=item B<--version>

Show the version and exit.

=back

=head1 ENVIRONMENT

=over

=item B<DPKG_ROOT>

If set and the B<--instdir> or B<--root> options have not been
specified, it will be used as the filesystem root directory.

=item B<DPKG_COLORS>

Sets the color mode.
The currently accepted values are: B<auto> (default), B<always> and B<never>.

=back

=head1 SEE ALSO

L<realpath(1)>.
