.TH dselect.cfg 5 "2011-07-03" "Debian Project" "dpkg suite"
.SH NAME
dselect.cfg \- dselect configuration file
.
.SH DESCRIPTION
This file contains default options for dselect. Each line contains a
single option which is exactly the same as a normal command line
option for dselect except for the leading dashes which are not used
here. Quotes surrounding option values are stripped. Comments are
allowed by starting a line with a hash sign ("\fB#\fR").
.
.SH FILES
.I /etc/dpkg/dselect.cfg.d/[0-9a-zA-Z_-]*
.br
.I /etc/dpkg/dselect.cfg
.br
.I ~/.dselect.cfg
.
.SH AUTHOR
See \fI/usr/share/doc/dpkg/THANKS\fP for the list of people who have
contributed to \fBdselect\fP.
.
.SH SEE ALSO
.BR dselect (1).
