.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\" (c) 2003 Software in the Public Interest
.\" Esta traducción ha sido realizada por N0K (N0K@oscuridad.com)
.\" Está basada en la página de manual original:
.\" versión 1.1 del CVS de /cvs/debian-doc/manpages/english/dpkg/822-date.1
.\" Autor: Ian Jackson

.TH 822\-DATE 1 "14 de agosto de 1996" "Proyecto Debian" "Herramientas de dpkg"
.SH NOMBRE 
822\-date \- Muestra la fecha y la hora en formato RFC822
.SH SINOPSIS
.B 822\-date
.SH DESCRIPCIÓN
.B 822\-date
muestra la fecha y la hora actual en  el formato descrito en RFC822,
usando un huso horario numérico compensado, como se recomienda en RFC1123	
.SH OPCIONES
.B 822\-date
no lleva ningún argumento u opción.
.SH FALLOS
Esta funcionalidad en realidad debería ser parte de 
.BR date (1),
.SH VÉASE TAMBIÉN
.I Standard for the Format of ARPA Internet Text Messages
(RFC822),
.br
.I Requirements for Internet Hosts -- Application and Support
(RFC1123) sección 5.2.14,
.br
.BR date (1).
.SH AUTOR
.B 822\-date
y este manual fueron escritos por Ian Jackson. Por la presente, fueron puestos en el dominio público por él.
.SH TRADUCTOR
Traducción de NOK <debian-l10n-spanish@lists.debian.org>
