.\" (c) 2003 Software in the Public Interest
.\" Esta traduccin ha sido realizada por Rubn Porras Campo <nahoo@inicia.es>
.\" Est basada en la pgina de manual original:
.\" versin 1.2 del CVS de
.\" /cvs/debian-doc/manpages/english/dpkg/dpkg-checkbuilddeps.1

.TH DPKG-CHECKBUILDDEPS 1 "febrero de 2001" "proyecto Debian" "utilidades dpkg"
.SH NOMBRE
dpkg-checkbuilddeps -- comprueba las dependencias y conflictos de compilacin.
.SH SINOPSIS
\fBdpkg-checkbuilddeps\fR -B [\fIfichero-control\fR]
.SH DESCRIPCIN
Este programa comprueba que los paquetes instalados en el sistema
satisfacen las dependencias y conflictos de construccin especificados
en el fichero de control del paquete. Si alguna de estas condiciones no se
cumple avisa y termina devolviendo un cdigo de error distinto de cero.
.P
Por omisin se lee \fBdebian/control\fR, pero puede especificarse un
fichero de control alternativo en la lnea de rdenes.
.SH OPCIONES
.TP
.I -B
Ignora las lneas Build-Depends-Indep. Usar cuando se construyen
paquetes independientes de la arquitectura.
.SH AUTOR
Copyright 2001 Joey Hess
.UR mailto:joeyh@debian.org
<joeyh@debian.org>
.UE
.sp
Esto es software libre, lea la Licencia Pblica General de GNU versin
2 o posterior para las condiciones de copia. NO hay ninguna garanta.
.SH TRADUCTOR
Traduccin de Rubn Porras Campo <debian-l10n-spanish@lists.debian.org>
