.\" Esta traduccin ha sido realizada por Bruno Barrera
.\" C. <bruno.barrera@igloo.cl>  y revisada por Javier Fernndez-Sanguino
.\" Est basada en la pgina de manual original:
.\" versin 1.1 del CVS de /cvs/debian-doc/manpages/english/dpkg/dpkg-deb.1

.TH "DPKG\-DEB" "1" "1st June 1996" "Proyecto Debian" "herramientas dpkg"
.SH "NOMBRE"
dpkg\-deb \- Herramienta de manipulacin de archivos de Debian (.deb)

.SH "SINOPSIS"
.B dpkg\-deb
.BR \-b | \-\-build
.I R directorio " [" archivo | directorio ]
.br 
.B dpkg\-deb
.BR \-I | \-\-info
.I R archivo " [" archivo\-de\-control " ..]"
.br 
.B dpkg\-deb
.BR \-f | \-\-field
.I R archivo " [" archivo\-de\-control " ...]"
.br 
.B dpkg\-deb
.BR \-c | \-\-contents
.I archivo
.br 
.B dpkg\-deb
.BR \-x | \-\-extract | \-X | \-\-vextract
.I archivo directorio
.br 
.B dpkg\-deb \-\-fsys\-tarfile
.I archivo
.br 
.B dpkg\-deb \-\-control
.I archivo directorio
.SH "DESCRIPCION"
.B dpkg\-deb
empaqueta, desempaqueta, y provee informacin sobre los archivos de Debian.

Use
.B dpkg
para instalar y eliminar paquetes de su sistema.

Tambin puede usar
.B dpkg\-deb
llamando a
.B dpkg
con cualquiera de las opciones que desee darle
.BR dpkg\-deb ".  " dpkg
le mostrar lo que necesite y
.B dpkg\-deb
lo ejecutar por usted.
.SH "OPCIONES DE USO"
.TP 
.BR \-\-build ", " \-b
Crea un archivo de Debian desde el sistema de archivos localizado en el
.IR directorio ".  " El directorio
debe tener un subdirectorio
.B DEBIAN
el cual contiene los archivos de informacin de control.
Este directorio
.I no
aparecer en el paquete binario, pero, en lugar de esto, los archivos
que tenga sern puestos en el rea de informacin del paquete binario.
Usted puede especificar el nivel de compresin usado con la opcin 
.B \-z#
.B dpkg-deb
pasar sta a gzip.

A menos que usted especifique
.BR \-\-nocheck ", " dpkg\-deb 
leer
.B DEBIAN/control
y lo revisar. Comprobar posibles errores de sintaxis y otros problemas,
y mostrar el nombre del paquete binario que se est creando.
.B dpkg\-deb
tambin comprobar los permisos de los programas del desarrollador as
como de los otros archivos que se encuentren en el directorio
.B DEBIAN
 .
Si no se especifica algn
.I archivo
, entonces
.B dpkg\-deb
crear el paquete en el fichero
.IR directorio \fB.deb\fR.

Si el archivo a ser creado ya existe entonces ser sobreescrito.

Si el segundo argumento es un directorio entonces
.B dpkg\-deb
escribir al archivo
.IB paquete _ versin _ arquitectura .deb\fR,
o
.IB paquete _ versin .deb
si el campo
.B Arquitecture
no est presente en el fichero de control del paquete. 
Cuando se especifica un directorio de destino
en lugar de un fichero, la opcin
.B \-\-nocheck
no debera utilizarse (dado que
.B dpkg\-deb
necesita leer y analizar el archivo de control del paquete para determinar 
qu nombre de archivo usar).
.TP 
.BR \-\-info ", " \-I
Ofrece informacin acerca del paquete binario.

Si se especifica
.I archivo(s)\-de\-control
entonces imprimir un resumen de los contenidos del paquete 
as como del archivo de control.

Si se especifica algn
.IR archivo\-de\-control
.B dpkg\-deb
imprimir stos en el orden que fueron especificados.
Si cualquiera de los componentes no estuviesen presentes, 
mostrar un mensaje de error a la salida de error estndar 
sobre cada uno de ellos y abortar con estado 2.
.TP 
.BR \-\-field ", " \-f
Extrae informacin del fichero de control del fichero de un paquete binario.

Si no se especifica ningn
.BR control\-file\-field s
entonces mostrar todo el fichero de control.

Si se especifica algn 
.B dpkg\-deb
mostrar sus contenidos, en el orden en el cual aparecen en el 
fichero de control. Si se especifica ms de un
.BR campo\-del\-fichero\-de\-control
, entonces
.B dpkg\-deb
preceder cada uno con el nombre del campo (ms dos puntos y espacio).

No se informa de ningn error para los campos que se hayan solicitados
pero que no se encuentren.
.TP 
.BR \-\-contents ", " \-c
Lista los contenidos de la parte del archivo que contiene los archivos
del sistema de ficheros. Se imprime en el formato generado por
.BR tar
cuando se selecciona listado extendido.

.TP 
.BR \-\-extract ", " \-x ", " \-\-vextract ", " \-X
Descomprime el rbol del sistema de ficheros desde el archivo del 
paquete en del directorio especificado.

.BR \-\-vextract " (" \-X ")"
Muestra una lista de los archivos extrados mientras que con la opcin
.BR \-\-extract " (" \-x ")"
no mostrar nada a menos que ocurra un error.

Nota, 
.I no
obtendr una instalacin correcta si extrae un paquete en el directorio raz!
Use 
.B dpkg
para instalar paquetes.

El 
.I directorio
(pero no los directorios previos) ser creado si fuera necesario.
.TP 
.BR \-\-fsys\-archivotar
Descomprime el rbol del sistema de archivos de un paquete binarios y lo 
enva hacia la salida estndar en formato
.B tar
\. Si se utiliza junto con
.B tar
se puede utilizar para descomprimir un fichero concreto de un paquete.
.TP 
.BR \-\-control ", " \-e
Descomprime los ficheros de informacin de control de un paquete dentro del
directorio especificado.

Si no se especifica ningn directorio se usar el subdirectorio
.B DEBIAN
en el directorio actual.

El directorio de destino (pero no los directorios previos) ser creado 
si fuera necesario.
.TP 
.BR \-\-help ", " \-h
Muestra la informacin de cmo usar
.BR dpkg\-deb 's
, con un resumen de sus opciones y usos.
.TP 
.BR \-\-version
Muestra el numero de versin de
.BR dpkg\-deb 's
.TP 
.BR \-\-licence
Muestra la informacin de licencia y garanta de
.BR dpkg\-deb 's
(El uso de la palabra americana
.B \-\-license
produce el mismo mensaje)
.SH "OTRAS OPCIONES"
.TP 
.BR \-\-new
Asegura que
.B dpkg\-deb
construye un `nuevo' formato de archivo. ste es el comportamiento por defecto.
.TP 
.BR \-\-old
Fuerza 
.B dpkg\-deb
a construir un `antiguo' formato de archivo.  Este formato antiguo 
de archivo es ms dificil de analizar por herramientas que no 
formen parte de Debian, por lo que ahora es obsoleto. Slo se usa
cuando se construyen paquetes que sern analizados por versiones de 
dpkg previas a la version
0.93.76 (septiembre 1995), la cual se distribuy slo para i386 en
formato a.out
.TP 
.BR \-\-nocheck
Impide las comprobaciones habituales de 
.BR "dpkg\-deb \-\-build" 's
sobre los contenidos del archivo. Puede construir
cualquier archivo que desee, no importa lo mal que est.
.TP 
.BR \-\-debug ", " \-D
Habilita los mensajes de depuracin. No son muy interesantes.
.SH "BUGS"
.B dpkg\-deb \-I 
.I B package1 .deb
.I B package2 .deb
no hace lo que debe hacer.

No existe ningn tipo de autentificacin en los arhivos
.B .deb
de hecho, no hay ni siquiera una cdigo de comprobacin directo.

No use 
.B dpkg\-deb
para instalar software! Debe usar
.B dpkg
para asegurarse de que todos los archivos se instalan en el sitio
correcto, que los guiones del paquete se ejecutan y que los 
contenidos de ste se registran.
.SH "VASE TAMBIN"
.BR deb (5),
.BR deb-control (5),
.BR dpkg (8),
.BR dselect (8).
.SH "AUTOR"
.B dpkg\-deb
y esta pgina de manual, fu escrita por Ian Jackson. Son
Copyright (c) 1995\-1996
suyos, y se distribuyen bajo la Licencia Publica de GNU.
No se ofrece NINGUNA garanta. 
Consulte
.B /usr/share/doc/dpkg/copyright
y
.B /usr/share/common-licenses/GPL
para ms informacin

Est pagina fue traducida por Bruno Barrera C. <bruno.barrera@igloo.cl>
y posteriormente revisada por Javier Fernndez-Sanguino.

