.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\" (c) 2003 Software in the Public Interest
.\" Traductor: Rubn Porras Campo <nahoo@inicia.es> y revisada
.\" por Santiago Vila <sanvila@unex.es>
.\" Basado en la versin 1.3 de 
.\" /cvs/debian-doc/manpages/english/dpkg/start-stop-daemon.8

.TH START\-STOP\-DAEMON 8 "15 de marzo de 1997" "Proyecto Debian" "Debian GNU/Linux"
.SH NOMBRE
start\-stop\-daemon \- para y arranca demonios del sistema
.SH SINOPSIS
.B start-stop-daemon
.BR -S | --start
.IR opciones
.RB [ \-\- ]
.IR argumentos
.HP
.B start-stop-daemon
.BR -K | --stop
.IR opciones
.HP
.B start-stop-daemon
.BR -H | --help
.HP
.B start-stop-daemon
.BR -V | --version
.SH DESCRIPCIN
.B start\-stop\-daemon
se usa para controlar la creacin y terminacin de los procesos del sistema.
Usando las opciones
.BR --exec ", " --pidfile ", " --user ", y " --name " opciones,"
.B start\-stop\-daemon
se puede configurar para encontrar distintos procesos del mismo demonio.

Con
.BR --start ,
.B start\-stop\-daemon
comprueba la existencia del proceso especificado.
Si este proceso ya existe,
.B start\-stop\-daemon
no hace nada, y termina con un estado de error 1 (0 si se especifica
.BR --oknodo
).
Si el proceso no existe, comienza uno nuevo, 
usando el ejecutable especificado por
.BR --exec ,
(o, si se especifica, por
.BR --startas
).
Cualquier argumento dado en la lnea de ordenes despus de
.BR --
se pasa sin modificacin alguna al programa que se va a ejecutar. Si se
especifica la opcin
.B --retry
entonces 
.B start-stop-daemon
comprobar que el proceso o los procesos han terminado.

Con 
.BR --stop ,
.B start\-stop\-daemon
comprueba adems la existencia del proceso especificado.
Si este proceso existe,
.B start\-stop\-daemon
enva la seal especificada por
.BR --signal ,
y termina con un estado de error 0.
Si este proceso no existe,
.B start\-stop\-daemon
termina con un estado de error 1 (0 si se ha especificado la opcin
.BR --oknodo
).

.SH OPCIONES

.TP
\fB-x\fP|\fB--exec\fP \fIejecutable\fP
Busca distintos procesos de este ejecutable (segn 
.B /proc/\fIpid\fB/exe\fP
).
.TP
\fB-p\fP|\fB--pidfile\fP \fIfichero-de-pid\fP
Comprueba si existen los procesos cuyo id corresponde con el
especificado en 
.IR fichero-de-pid .
.TP
\fB-u\fP|\fB--user\fP \fInombre-usuario\fP|\fIuid\fP
Comprueba si existen los procesos del usuario especificado por
.I nombre-usuario
o
.IR uid .
.TP
\fB-g\fP|\fB--group\fP \fIgrupo\fP|\fIgid\fP
Cambia a \fIgrupo\fP o \fIgid\fP cuando comienza el proceso.
.TP
\fB-n\fP|\fB--name\fP \fInombre-proceso\fP
Comprueba los procesos con el nombre
.I nombre-proceso
(segn
.BR /proc/\fIpid\fB/stat\fP ).
.TP
\fB-s\fP|\fB--signal\fP \fIseal\fP
Junto con
.BR --stop ,
especifica la seal enviada al proceso que se desea parar (15 por omisin).
.TP
\fB-R\fP|\fB--retry\fP \fItiempo-de-espera\fP|\fIaccin-programada\fP
Junto con
.BR --stop ,
especifica que
.B start-stop-daemon
compruebe que el proceso o los procesos han terminado.  Lo comprobar 
repetidas veces hasta que no haya ningn proceso que coincida. Si el proceso 
no termina tomar una decisin determinada por 
.I accin-programada .

Si se especifica
.I tiempo-de-espera
en vez de
.I accin-programada
entonces se usa la secuencia
.IB seal / tiempo-de-espera /KILL/ tiempo-de-espera
, donde
.I seal
es la seal especificada por
.BR --signal .

.I accin-programada
es una lista de al menos dos artculos separados por barras
.RB ( / );
cada artculo puede ser un
.BI - nmero de seal
o [\fB\-\fP]\fInombre de seal\fP,
que significa que se debe mandar esa seal, o
.IR tiempo-de-espera,
que significa que se debe esperar esos segundos para que el programa
termine, o
.BR forever ,
que significa que se repite el resto de accin-programada para siempre 
si es necesario.

Si se alcanza el final de la accin-programada y no se ha especificado
.BR forever
, entonces
.B start-stop-daemon
termina con un estado de error 2.
Si se especifica una secuencia, entonces cualquier seal especificada
con
.B --signal
no se tendr en cuenta.
.TP
\fB-a\fP|\fB--startas\fP \fIpathname\fP
Con 
.BR --start ,
comienza el proceso especificado por
.IR pathname .
Si no se especifica, se usarn los argumentos dados con
.BR --exec .
.TP
.BR -t | --test
Muestra las acciones que se realizaran y devuelve el valor
apropiado, pero no hace nada.
.TP
.BR -o | --oknodo
Devuelve un estado 0 en vez de 1 si no se realiza (realizasen)
ninguna accin.
.TP
.BR -q | --quiet
No muestra mensajes informativos, slo muestra mensajes de error.
.TP
\fB-c\fP|\fB--chuid\fP \fInombre-usuario\fR|\fIuid\fP
Cambia a este usuario/uid antes de empezar el proceso. Adems puede
especificar el grupo aadiendo
.BR : ,
luego el grupo o el gid del mismo modo que hara con la orden
`chown' (\fIusuario\fP\fB:\fP\fIgrupo\fP).
Debe de darse cuenta que cuando se usa esta opcin el grupo primario
y complementario se cambian tambin, incluso si no se especifica
.B --group .
La opcin 
.B --group
es slo para grupos de los que el usuario no es miembro (como el grupo
nobody ).
.TP
\fB-r\fP|\fB--chroot\fP \fIdirectorio-raz
Efectua chdir y chroot a
.I directorio-raz
antes de empezar el proceso. Dese cuenta que el fichero del pid
tambin es escrito despus de hacer el chroot.
.TP
\fB-d\fP|\fB--chdir\fP \fIdirectorio\fP
Efectua chdir a
.I directorio
antes de empezar el proceso. Esto se hace despus de efectuar chroot, si es que
la opcin
\fB-r\fP|\fB--chroot\fP est establecida.
.TP
.BR -b | --background
Usado tpicamente con programas que no se separan por s mismos. Esta
opcin forzar
.B start-stop-daemon
a hacer fork antes de empezar el proceso, y luego dejarlo en segundo plano.
.B ATENCIN: start-stop-daemon
no puede comprobar el estado de salida si el proceso no puede ejecutarse
por 
.B cualquier
razn. Esto se hace como ltimo recurso, y slo tiene sentido usarla en 
programas donde no tiene sentido que hagan fork por s mismos, o no es
factible aadir el cdigo para que lo hagan por s mismos.
.TP
\fB-N\fP|\fB--nicelevel\fP \fIentero\fP
Altera la prioridad del proceso antes de empezarlo.
.TP
.BR -m | --make-pidfile
Se usa cuando se quiere comenzar un programa que no crea su propio
fichero de pid. Esta opcin hace que
.B start-stop-daemon
cree el fichero referido con
.B --pidfile
y coloque el pid dentro de l justo antes de ejecutar el
proceso. Dese cuenta que no se borrar cuando termine el programa.
.B NOTA:
Esta caracterstica no funciona en todos los casos. Ms notablemente
cuando el programa que se ejecuta hace fork en su proceso principal.
Por esto solamente es til cuando se combina con la opcin
.B --background .
.TP
.BR -v | --verbose
Muestra mensajes informativos detallados.
.TP
.BR -H | --help
Muestra la ayuda y luego termina.
.TP
.BR -V | --version
Muestra la versin y luego termina.

.SH AUTORES
Marek Michalkiewicz <marekm@i17linuxb.ists.pwr.wroc.pl> basada en una
versin previa de Ian Jackson <ian@chiark.greenend.org.uk>.

Pgina del manual de Klee Dienes <klee@mit.edu>, reformada
parcialmente por Ian Jackson.

Traducida por Rubn Porras <nahoo@inicia.es>
Revisada por Santiago Vila <sanvila@unex.es>
