#!/bin/sh

top_srcdir=`dirname $0`

# To avoid using «readlink -f» or «realpath» we just change into the
# desired directory and work from there.
cd "$top_srcdir"

# Set up the environment, to use local perl modules and data files.
export PERL5LIB=`pwd`/scripts:`pwd`/dselect/methods
export DPKG_DATADIR=`pwd`

exec "$@"
