#!/bin/sh

set -e

if [ "$(id -u)" != '0' ]; then
  # Fail, we declared needing root as a restriction.
  exit 1
fi

srcdir="$(pwd)"

cd $AUTOPKGTEST_TMP
"$srcdir/configure" --disable-nls --disable-dselect
make installcheck TESTSUITEFLAGS=--verbose
