#!/bin/sh

set -e

export DPKG_TESTSUITE_OPTIONS="debug"
export DPKG_ADMINDIR="$AUTOPKGTEST_TMP/db"
export DPKG_INSTDIR="$AUTOPKGTEST_TMP/root"

mkdir -p "$DPKG_INSTDIR"
eatmydata make -C tests test DPKG_INSTDIR="$DPKG_INSTDIR" DPKG_ADMINDIR="$DPKG_ADMINDIR"
