#!/bin/sh

set -e

if [ "$(id -u)" != '0' ]; then
  # Fail, we declared needing root as a restriction.
  exit 1
fi

t=test-root

mkdir -p $t
cd $t
../configure --disable-nls --disable-dselect
make installcheck
