#!/bin/sh

set -e

if [ -e /trigger-$DPKG_MAINTSCRIPT_NAME ]; then
    if [ -e /trigger-noawait ]; then
	echo "Executing 'dpkg-trigger --no-await a-trigger' from '$0 $1'"
	dpkg-trigger --no-await a-trigger
    else
	echo "Executing 'dpkg-trigger a-trigger' from '$0 $1'"
	dpkg-trigger a-trigger
    fi
fi

