#!/bin/sh
set -e

case "$1" in
  triggered)
    pkg_status=`dpkg-query -f '${Status}' -W pkg-depended`
    if [ "$pkg_status" = "install ok installed" ]; then
      echo "Pass: pkg-depended is installed"
    else
      echo "Fail: pkg-depended is not installed ($pkg_status)"
      exit 1
    fi
  ;;
esac

exit 0
