.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\" Authors: Ian Jackson
.\" original cvs revision: 1.2
.TH 822\-DATE 1 "14th August 1996" "Debian Project" "dpkg utilities"
.SH 名前
822\-date \- RFC822フォーマットの日付と時間の印字
.SH 書式
.B 822\-date
.SH 説明
.B 822\-date
は RFC822 に説明されているフォーマット、RFC1123 で推奨されている数字に
よるタイムゾーンオフセットを使って現在の日付と時間を表示します。
.SH オプション
.B 822\-date
には引数、オプションはありません。
.SH バグ
この機能は実際には
.BR date (1)
の一部であるべきです。
.SH 関連項目
.I ARPAインターネットテキストメッセージのフォーマットの標準 (Standard for the Format of ARPA Internet Text Messages)
(RFC822),
.br
.I インターネットホストへの要求事項 -- アプリケーションとサポート (Requirements for Internet Hosts -- Application and Support)
(RFC1123) 5.2.14 節,
.br
.BR date (1)
.SH 著者
.B 822\-date
と このマニュアルページは Ian Jackson によってかかれ、彼によって
public domain なものとしてここに含まれています。
.SH 翻訳者
石川睦 <ishikawa@linux.or.jp>
