.\" original cvs revision: 1.1
.TH CLEANUP-INFO 8 "November 1999" "Debian Project" "dpkg utilities"
.SH 名前
cleanup-info \- install-info の誤った利用による混乱の消去
.SH 書式
.B cleanup-info
[--help] [--unsafe] [--version] [--] [\fI<ディレクトリ名>\fP]
.SH 説明
.B cleanup-info
は install-info の誤った適用によって生じた混乱を消去するための Perl スクリ
プトである。同じ表題を持ったセクションを一つにまとめ、大文字小文字の区
別、あとに続くコロン/スペースに関しても賢く処理しようとする。
.br
その他、空のセクションの除去、空行の圧縮(エントリーパートのみ)も
行われる。
.sp
セクションの順序は保存される(複数同じエントリがあった場合、最初に
発見されたものの位置になる)。
セクション内でのエントリの順序も保存される。
.sp
このユーティリティの使用は\fB特別注意深く\fP行って欲しい - おそらく、
このユーティリティは 100% 安全ではない。cleanup-info は 注意深く
info dir ファイルを扱おうとするが、ファイルに書いてしまえば
それまでである。このユーティリティを使う前にバックアップファイルを
とるようにすべきである。
.SH オプション
.TP
.I --help
ヘルプを表示し、正常終了する。
.TP
.I --unsafe
いくつかの付加的なおそらく有用であろうオプションをセットする。
.br
.B "警告: `--unsafe' オプションは正しいファイルを改竄してしまうかもしれません!"
.TP
.I --version
バージョンを表示し、正常終了する。
.SH ファイル
.TP
.I "/usr/info/dir または <ディレクトリ名>/dir"
info ディレクトリファイル。ロックファイルは同じ名前で ".lock" 拡張子が
ついたものになる。
.SH バグ
おそらくたくさんある。
.SH 関連項目
.BR install-info (8),
.BR info (1).
.SH 著者
Copyright (C) 1996 Kim-Minh Kaplan.
.sp
This is free software; see the GNU General Public Licence
version 2 or later for copying conditions.  There is NO warranty.
.SH 翻訳者
石川睦 <ishikawa@linux.or.jp>
