.\"original revision: 1.1
.TH DEB-OLD 5 "January 2000" "Debian Project" "Debian"
.SH 名称
deb-old - Debian バイナリパッケージ旧形式フォーマット
.SH 書式
.IB filename .deb
.SH 説明
.B .deb
フォーマットは Debian バイナリパッケージのファイル形式である。
このマニュアルでは、Debian 0.93 以前に使用されていた
.B 旧形式
について記述する。新形式の詳細については
.BR deb (5)
を参照されたい。
.SH フォーマット
2 行のフォーマット情報を ASCII テキストファイルがあり、それに 2 つの
圧縮 tar ファイルが続く。
.PP
1 行目は 8 桁にそろえたフォーマットバージョン番号であり、
旧形式アーカイブはすべて
.B 0.939000
である。
.PP
2 行目はひとつ目の圧縮 tar ファイルの大きさを与える(0 から始まらない)
十進数である。
.PP
それぞれの行の終わりは改行文字ひとつである。
.PP
1 番目の tar ファイルは、制御情報を平文ファイル群として含む。詳細は
.IR "Debian Packaging Manual, section 2.2".
に記述されている。
.B control
ファイルは必須であり、中心となる制御情報を含む。
.PP
非常に古いアーカイブでは、
control tar ファイル中のファイルが
.B DEBIAN
サブディレクトリにあることもある。この場合、
control tar ファイルにも
.B DEBIAN
サブディレクトリが存在し、
control tar ファイルはそのディレクトリ内にのみファイルを保有する。
control tar ファイルは、
.RB ` . ',
つまりカレントディレクトリにファイルを含むこともある。
.PP
2 番目の圧縮 tar ファイルはファイルシステムアーカイブであり、
インストールされるシステムのルートディレクトリからの相対パス名を
含んでいる。パス名の先頭にスラッシュ(/)はない。

.SH 関連項目
.BR deb (5),
.BR dpkg-deb (1),
.BR deb-control (5),
.IR "Debian Packaging Manual".
.SH 翻訳者
鍋谷 栄展 <nabe@debian.or.jp>
