#!/bin/sh
if dpkg-maintscript-helper supports mv_conffile; then
    dpkg-maintscript-helper mv_conffile /test-conffile-old /test-conffile-new 0 -- "$@"
fi

if [ -e /fail-preinst ]; then
    exit 1
fi

