#!/bin/sh

set -e

args="$@"

while [ $# -gt 0 ]; do
  opt="$1"
  shift

  case "$opt" in
  --print-architecture)
    echo amd64
    exit 0
  esac
done

# Otherwise fail hard.
echo "$0: unsupported command ($args) in mock wrapper"
exit 1
