#!/bin/sh
set -e

case "$1" in
  triggered)
    if [ -e /test/trigger/test-file ]; then
      touch "${DPKG_ROOT}/test-triggered-file"
    else
      touch "${DPKG_ROOT}/test-triggered-cmd"
    fi
  ;;
esac

exit 0
