.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\" Author: Raul Miller
.\" Includes text from the debian Guidelines by Ian Jackson, Ian Murdock
.TH DEB-CONTROL 5 "29th November 1995" "Debian Project" "Debian GNU/Linux"
.SH NAME
deb\-control \- Debian GNU/Linux packages' master control file format
.SH SYNOPSIS
control
.SH DESCRIPTION
Master control file format:
.LP
The `control' file contains a number of fields.  Each field begins
with a tag, such as `PACKAGE' or `VERSION' (case insensitive),
followed by a colon, and the body of the field. Fields are delimited
only by field tags.  In other words, field text may be multiple lines
in length, but the installation tools will generally join lines when
processing the body of the field.
.SH REQUIRED FIELDS
.TP
.BR PACKAGE: \ <Short\ name\ of\ package>
The value of this field is used to generate file names by some
installation tools.
.TP
.BR VERSION: \ <Original\ version\ number>
typically, this is the original portable package's version
number in whatever form the program's author uses.
.TP
.BR PACKAGE_REVISION: \ <Debian\ package\ revision\ number>
this should usually be a plain number, or perhaps two numbers
separated by a full stop.
.TP
.BR MAINTAINER: \ <Name\ and\ e-mail\ address\ of\ package\ maintainer>
should be in the format  Joe Bloggs <jbloggs@foo.com>.
.TP
.BR DESCRIPTION: \ <Description\ of\ package> 
.SH OPTIONAL FIELDS
.TP
.BR DEPENDS: \ <Short\ names\ of\ prerequisite\ packages>
list of packages that are required for this package to provide a
non-trivial amount of functionality.  The package maintenance software
will not allow a package to be installed without also installing
packages listed in its 
.B DEPENDS
field, and will rin the postinst scripts of packages listed in DEPENDS
fields before those of the packages which depend on them, and run
prerm scripts before.
.TP
.BR RECOMMENDED: \ <Short\ names\ of\ related,\ recommended\ packages>
lists packages that would be found together with
this one in all but unusual installations.  The package maintenance
software will warn the user if they install a package without those
listed in its
.B RECOMMENDED
field.
.LP
The syntax of
.B DEPENDS
and
.B RECOMMENDED
is a list of groups of alternative packages.  Each group is a list of
packages separated by vertical bar (or `pipe') symbols, `|'.  The
groups are separated by commas.  Each package is a package name
optionally followed by a version number specification in parentheses.
A version number may start with a `>', in which case any later version
will match, and may specify or omit the Debian packaging revision
(separated by a hyphen).  Commas are to be read as `AND', and pipes as
`OR', with pipes binding more tightly.
.TP
.BR OPTIONAL: \ <Short\ names\ of\ related,\ optional\ packages>
lists packages that are related to this one and can perhaps enhance
its usefulness, but without which installing this package is perfectly
reasonable.  The package maintenance software will not moan at the
user for not selecting
.B OPTIONAL
related packages, but may use the information in the
.B OPTIONAL
field to assist the user during package selection.
.TP
.BR CONFLICTS: \ <Short\ names\ of\ packages\ which\ conflict\ with\ this\ one>
lists packages that conflict with this one, for example by containing
files with the same names (an example would be Smail vs. Sendmail).
The package maintenance software will not allow conflicting packages
to be installed.  Two conflicting packages should each include a
.B CONFLICTS
line mentioning the other.
.LP
The syntax of
.B OPTIONAL
and
.B CONFLICTS
is a list of package names, separated by commas (and optional
whitespace).  In the
.B CONFLICTS
field, the comma should be read as `OR'.

.SH BUGS
This manpage is seriously out of date.

.SH SEE ALSO
.BR deb (5),
.BR dpkg (5),
.BR dpkg (8),
.BR dpkg-dep (8),
.BR dselect (8).
