{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginTheoremCounter {}}
{@LVis @TheoremCounterMarker
   @Tag { "3278.policy.lout.1" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginDefinitionCounter {}}
{@LVis @DefinitionCounterMarker
   @Tag { "3336.policy.lout.1" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginClaimCounter {}}
{@LVis @ClaimCounterMarker
   @Tag { "3391.policy.lout.1" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginPropositionCounter {}}
{@LVis @PropositionCounterMarker
   @Tag { "3445.policy.lout.1" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginLemmaCounter {}}
{@LVis @LemmaCounterMarker
   @Tag { "3500.policy.lout.1" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginCorollaryCounter {}}
{@LVis @CorollaryCounterMarker
   @Tag { "3554.policy.lout.1" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginExampleCounter {}}
{@LVis @ExampleCounterMarker
   @Tag { "3609.policy.lout.1" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{Yes @LVis @BeginDisplayCounter {}}
@LEnv
{@LUse @DocumentLayout}
{Yes @LVis @BeginDisplayCounter {}}
{?? @LVis @Then ??}
{@LVis y}
@LClos
{@LVis @NumDispCounterMarker
   @Tag { "1400.policy.lout.1" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FigurePrefixMarker
   @Tag { "4153.policy.lout.1" }
   prefix {  }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FigureCounterMarker
   @Tag { "4161.policy.lout.1" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @TablePrefixMarker
   @Tag { "4334.policy.lout.1" }
   prefix {  }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @TableCounterMarker
   @Tag { "4342.policy.lout.1" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginDefinitionCounter {}}
{@LVis @DefinitionCounterMarker
   @Tag { "3336.policy.lout.2" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginClaimCounter {}}
{@LVis @ClaimCounterMarker
   @Tag { "3391.policy.lout.2" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginPropositionCounter {}}
{@LVis @PropositionCounterMarker
   @Tag { "3445.policy.lout.2" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginLemmaCounter {}}
{@LVis @LemmaCounterMarker
   @Tag { "3500.policy.lout.2" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginCorollaryCounter {}}
{@LVis @CorollaryCounterMarker
   @Tag { "3554.policy.lout.2" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginExampleCounter {}}
{@LVis @ExampleCounterMarker
   @Tag { "3609.policy.lout.2" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @PageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
   extra { Yes }
1}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
   extra { Yes }
   @AtTop { @LVis @AtTop }
1}
{@PageMarker
   @Tag { "582.policy.lout.1" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.1" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{Start @Runner
   @Tag { "1954.policy.lout.3" }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @PageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
   extra { Yes }
1}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
   extra { Yes }
   @AtTop { @LVis @AtTop }
1}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
2}
{@PageMarker
   @Tag { "582.policy.lout.2" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.2" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
3}
{@PageMarker
   @Tag { "582.policy.lout.3" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.3" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
3}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
4}
{@PageMarker
   @Tag { "582.policy.lout.4" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.4" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.1" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.1" }
{That any user be able to rebuild any package in the official Debian
distribution from the original source plus our patches.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.2" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.2" }
{That we make available in our packaging formats as much software as we
can.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.3" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.3" }
{That it be easy for people to make CDROMs of our distribution without
violating copyrights.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
5}
{@PageMarker
   @Tag { "582.policy.lout.5" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.5" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.policy.lout.1" }
{This applies in
the United States, too.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.policy.lout.1"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.6" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.policy.lout.1"}
{@LVis @NumberMarker
   @Tag { "2521.policy.lout.1" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
5}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
6}
{@PageMarker
   @Tag { "582.policy.lout.6" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.7" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
7}
{@PageMarker
   @Tag { "582.policy.lout.7" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.8" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.policy.lout.2" }
{In a sense everything is optional that
isn't required, but that's not what is meant here.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.policy.lout.2"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.9" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.policy.lout.2"}
{@LVis @NumberMarker
   @Tag { "2521.policy.lout.2" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
7}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
8}
{@PageMarker
   @Tag { "582.policy.lout.8" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.10" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
9}
{@PageMarker
   @Tag { "582.policy.lout.9" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.11" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.policy.lout.3" }
{Where {Times Slope} @Font package is the
name of the package.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.policy.lout.3"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.12" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.policy.lout.3"}
{@LVis @NumberMarker
   @Tag { "2521.policy.lout.3" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
9}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
10}
{@PageMarker
   @Tag { "582.policy.lout.10" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.13" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
11}
{@PageMarker
   @Tag { "582.policy.lout.11" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.14" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
11}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
12}
{@PageMarker
   @Tag { "582.policy.lout.12" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.15" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
13}
{@PageMarker
   @Tag { "582.policy.lout.13" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.16" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
13}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
14}
{@PageMarker
   @Tag { "582.policy.lout.14" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.17" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.policy.lout.4" }
{{Times Slope} @Font soname is
the shared object name of the shared library "-" it's the thing that has
to match exactly between building an executable and running it for the
dynamic linker to be able run the program. Usually the {Times Slope} @Font soname
is the major number of the library.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.policy.lout.4"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.18" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.policy.lout.4"}
{@LVis @NumberMarker
   @Tag { "2521.policy.lout.4" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
15}
{@PageMarker
   @Tag { "582.policy.lout.15" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.19" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
15}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
16}
{@PageMarker
   @Tag { "582.policy.lout.16" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.20" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.policy.lout.5" }
{An MTA's prompting
configuration script may wish to prompt the user even if it finds this
file exists.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.policy.lout.5"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.21" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.policy.lout.5"}
{@LVis @NumberMarker
   @Tag { "2521.policy.lout.5" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
17}
{@PageMarker
   @Tag { "582.policy.lout.17" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.22" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.policy.lout.6" }
{If an attacker can subvert any "set-user-id" game
they can overwrite the executable of any other, causing other players
of these cames to run a trojan. With a "set-group-id" game the attacker
only gets access to less important game data, and if they can get at
the other players' accounts at all it will take considerably more
effort.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.policy.lout.6"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.23" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.policy.lout.6"}
{@LVis @NumberMarker
   @Tag { "2521.policy.lout.6" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
17}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
18}
{@PageMarker
   @Tag { "582.policy.lout.18" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.24" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
19}
{@PageMarker
   @Tag { "582.policy.lout.19" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.25" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
19}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
20}
{@PageMarker
   @Tag { "582.policy.lout.20" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.26" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.policy.lout.7" }
{You will need to agree that the parser and its
manpage may be distributed under the GNU GPL, just as the rest of
{0.7 1.0} @Scale {{Courier Bold} @Font dpkg} is.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.policy.lout.7"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.27" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.policy.lout.7"}
{@LVis @NumberMarker
   @Tag { "2521.policy.lout.7" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
21}
{@PageMarker
   @Tag { "582.policy.lout.21" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.28" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
21}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
22}
{@PageMarker
   @Tag { "582.policy.lout.22" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.29" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.4" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.4" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.5" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.5" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.6" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.6" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 4}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.7" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.7" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 5}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.8" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.8" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 6}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.9" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.9" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 7}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.10" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.10" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 8}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.11" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.11" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 9}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.12" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.12" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 10}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.13" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.13" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 11}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.14" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.14" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 12}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.15" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.15" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
23}
{@PageMarker
   @Tag { "582.policy.lout.23" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.30" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.policy.lout.8" }
{where
{0.7 1.0} @Scale {{Courier Bold} @Font {"debian"{--}""{{1.4285714285 1.0} @Scale {{Times Slope} @Font foo}}}} is the name of the list}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.policy.lout.8"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.31" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.policy.lout.8"}
{@LVis @NumberMarker
   @Tag { "2521.policy.lout.8" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
23}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
24}
{@PageMarker
   @Tag { "582.policy.lout.24" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.32" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.16" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.16" }
{Download the original source code from wherever it can be found and do
any rearrangement required to make it look like the original tree of
the Debian source. Put it in
{0.7 1.0} @Scale {{Courier Bold} @Font {{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}{""{--}""}{{1.4285714285 1.0} @Scale {{Times Slope} @Font "upstream-version"}}".orig/"}} or
{{0.7 1.0} @Scale {{Courier Bold} @Font {{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}_{{1.4285714285 1.0} @Scale {{Times Slope} @Font "upstream-version"}}{.orig.tar.gz}}}}.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.17" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.17" }
{Rename all files {0.7 1.0} @Scale {{Courier Bold} @Font {debian.*}} to {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/*"}}. There may be some
exceptions to this, but this is a good start.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.18" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.18" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }}
{@LVis @MakeList 4}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.19" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.19" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.19" }
{"Edit/create" {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/control"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font Version} field. If it is generated unusually (not
equal to the source version) you must use the "-v" option to
"dpkg-gencontrol" (see below). {{0.7 1.0} @Scale {{Courier Bold} @Font Section}}, {{0.7 1.0} @Scale {{Courier Bold} @Font Priority}},
{0.7 1.0} @Scale {{Courier Bold} @Font Maintainer} go above the first blank line, most of the rest below.}
// @LVis listitem {Reorder the fields and add a blank line at an appropriate point,
separating the source package fields from the binary package
fields.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font Source} field.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font {"Standards"{--}"Version"}} field. The current value is
{{0.7 1.0} @Scale {{Courier Bold} @Font {0.2.0.0}}}.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field for each package to {{0.7 1.0} @Scale {{Courier Bold} @Font any}},
{0.7 1.0} @Scale {{Courier Bold} @Font all} or whatever. If there isn't an {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field add
one.}
// @LVis listitem {If any other seddery or things used to happen to make the binary
control files use {{0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}}}{'s} variable substitution
features to achieve the same effect. Use {0.7 1.0} @Scale {{Courier Bold} @Font "debian/substvars"} if
you need to put "unusally-generated" information (apart from details of
{0.7 1.0} @Scale {{Courier Bold} @Font {.deb}} files) in the {0.7 1.0} @Scale {{Courier Bold} @Font {.changes}} file too.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.20" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.19" }
{"Edit/create" {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/control"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font Version} field. If it is generated unusually (not
equal to the source version) you must use the "-v" option to
"dpkg-gencontrol" (see below). {{0.7 1.0} @Scale {{Courier Bold} @Font Section}}, {{0.7 1.0} @Scale {{Courier Bold} @Font Priority}},
{0.7 1.0} @Scale {{Courier Bold} @Font Maintainer} go above the first blank line, most of the rest below.}
// @LVis listitem {Reorder the fields and add a blank line at an appropriate point,
separating the source package fields from the binary package
fields.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font Source} field.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font {"Standards"{--}"Version"}} field. The current value is
{{0.7 1.0} @Scale {{Courier Bold} @Font {0.2.0.0}}}.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field for each package to {{0.7 1.0} @Scale {{Courier Bold} @Font any}},
{0.7 1.0} @Scale {{Courier Bold} @Font all} or whatever. If there isn't an {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field add
one.}
// @LVis listitem {If any other seddery or things used to happen to make the binary
control files use {{0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}}}{'s} variable substitution
features to achieve the same effect. Use {0.7 1.0} @Scale {{Courier Bold} @Font "debian/substvars"} if
you need to put "unusally-generated" information (apart from details of
{0.7 1.0} @Scale {{Courier Bold} @Font {.deb}} files) in the {0.7 1.0} @Scale {{Courier Bold} @Font {.changes}} file too.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.policy.lout.20" }
{Remove the {0.7 1.0} @Scale {{Courier Bold} @Font Version} field. If it is generated unusually (not
equal to the source version) you must use the "-v" option to
"dpkg-gencontrol" (see below). {{0.7 1.0} @Scale {{Courier Bold} @Font Section}}, {{0.7 1.0} @Scale {{Courier Bold} @Font Priority}},
{0.7 1.0} @Scale {{Courier Bold} @Font Maintainer} go above the first blank line, most of the rest below.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.19" }
{"Edit/create" {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/control"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font Version} field. If it is generated unusually (not
equal to the source version) you must use the "-v" option to
"dpkg-gencontrol" (see below). {{0.7 1.0} @Scale {{Courier Bold} @Font Section}}, {{0.7 1.0} @Scale {{Courier Bold} @Font Priority}},
{0.7 1.0} @Scale {{Courier Bold} @Font Maintainer} go above the first blank line, most of the rest below.}
// @LVis listitem {Reorder the fields and add a blank line at an appropriate point,
separating the source package fields from the binary package
fields.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font Source} field.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font {"Standards"{--}"Version"}} field. The current value is
{{0.7 1.0} @Scale {{Courier Bold} @Font {0.2.0.0}}}.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field for each package to {{0.7 1.0} @Scale {{Courier Bold} @Font any}},
{0.7 1.0} @Scale {{Courier Bold} @Font all} or whatever. If there isn't an {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field add
one.}
// @LVis listitem {If any other seddery or things used to happen to make the binary
control files use {{0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}}}{'s} variable substitution
features to achieve the same effect. Use {0.7 1.0} @Scale {{Courier Bold} @Font "debian/substvars"} if
you need to put "unusally-generated" information (apart from details of
{0.7 1.0} @Scale {{Courier Bold} @Font {.deb}} files) in the {0.7 1.0} @Scale {{Courier Bold} @Font {.changes}} file too.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.21" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.19" }
{"Edit/create" {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/control"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font Version} field. If it is generated unusually (not
equal to the source version) you must use the "-v" option to
"dpkg-gencontrol" (see below). {{0.7 1.0} @Scale {{Courier Bold} @Font Section}}, {{0.7 1.0} @Scale {{Courier Bold} @Font Priority}},
{0.7 1.0} @Scale {{Courier Bold} @Font Maintainer} go above the first blank line, most of the rest below.}
// @LVis listitem {Reorder the fields and add a blank line at an appropriate point,
separating the source package fields from the binary package
fields.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font Source} field.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font {"Standards"{--}"Version"}} field. The current value is
{{0.7 1.0} @Scale {{Courier Bold} @Font {0.2.0.0}}}.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field for each package to {{0.7 1.0} @Scale {{Courier Bold} @Font any}},
{0.7 1.0} @Scale {{Courier Bold} @Font all} or whatever. If there isn't an {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field add
one.}
// @LVis listitem {If any other seddery or things used to happen to make the binary
control files use {{0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}}}{'s} variable substitution
features to achieve the same effect. Use {0.7 1.0} @Scale {{Courier Bold} @Font "debian/substvars"} if
you need to put "unusally-generated" information (apart from details of
{0.7 1.0} @Scale {{Courier Bold} @Font {.deb}} files) in the {0.7 1.0} @Scale {{Courier Bold} @Font {.changes}} file too.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.policy.lout.21" }
{Reorder the fields and add a blank line at an appropriate point,
separating the source package fields from the binary package
fields.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.19" }
{"Edit/create" {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/control"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font Version} field. If it is generated unusually (not
equal to the source version) you must use the "-v" option to
"dpkg-gencontrol" (see below). {{0.7 1.0} @Scale {{Courier Bold} @Font Section}}, {{0.7 1.0} @Scale {{Courier Bold} @Font Priority}},
{0.7 1.0} @Scale {{Courier Bold} @Font Maintainer} go above the first blank line, most of the rest below.}
// @LVis listitem {Reorder the fields and add a blank line at an appropriate point,
separating the source package fields from the binary package
fields.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font Source} field.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font {"Standards"{--}"Version"}} field. The current value is
{{0.7 1.0} @Scale {{Courier Bold} @Font {0.2.0.0}}}.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field for each package to {{0.7 1.0} @Scale {{Courier Bold} @Font any}},
{0.7 1.0} @Scale {{Courier Bold} @Font all} or whatever. If there isn't an {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field add
one.}
// @LVis listitem {If any other seddery or things used to happen to make the binary
control files use {{0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}}}{'s} variable substitution
features to achieve the same effect. Use {0.7 1.0} @Scale {{Courier Bold} @Font "debian/substvars"} if
you need to put "unusally-generated" information (apart from details of
{0.7 1.0} @Scale {{Courier Bold} @Font {.deb}} files) in the {0.7 1.0} @Scale {{Courier Bold} @Font {.changes}} file too.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.22" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.19" }
{"Edit/create" {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/control"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font Version} field. If it is generated unusually (not
equal to the source version) you must use the "-v" option to
"dpkg-gencontrol" (see below). {{0.7 1.0} @Scale {{Courier Bold} @Font Section}}, {{0.7 1.0} @Scale {{Courier Bold} @Font Priority}},
{0.7 1.0} @Scale {{Courier Bold} @Font Maintainer} go above the first blank line, most of the rest below.}
// @LVis listitem {Reorder the fields and add a blank line at an appropriate point,
separating the source package fields from the binary package
fields.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font Source} field.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font {"Standards"{--}"Version"}} field. The current value is
{{0.7 1.0} @Scale {{Courier Bold} @Font {0.2.0.0}}}.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field for each package to {{0.7 1.0} @Scale {{Courier Bold} @Font any}},
{0.7 1.0} @Scale {{Courier Bold} @Font all} or whatever. If there isn't an {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field add
one.}
// @LVis listitem {If any other seddery or things used to happen to make the binary
control files use {{0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}}}{'s} variable substitution
features to achieve the same effect. Use {0.7 1.0} @Scale {{Courier Bold} @Font "debian/substvars"} if
you need to put "unusally-generated" information (apart from details of
{0.7 1.0} @Scale {{Courier Bold} @Font {.deb}} files) in the {0.7 1.0} @Scale {{Courier Bold} @Font {.changes}} file too.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.policy.lout.22" }
{Add the {0.7 1.0} @Scale {{Courier Bold} @Font Source} field.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.19" }
{"Edit/create" {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/control"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font Version} field. If it is generated unusually (not
equal to the source version) you must use the "-v" option to
"dpkg-gencontrol" (see below). {{0.7 1.0} @Scale {{Courier Bold} @Font Section}}, {{0.7 1.0} @Scale {{Courier Bold} @Font Priority}},
{0.7 1.0} @Scale {{Courier Bold} @Font Maintainer} go above the first blank line, most of the rest below.}
// @LVis listitem {Reorder the fields and add a blank line at an appropriate point,
separating the source package fields from the binary package
fields.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font Source} field.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font {"Standards"{--}"Version"}} field. The current value is
{{0.7 1.0} @Scale {{Courier Bold} @Font {0.2.0.0}}}.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field for each package to {{0.7 1.0} @Scale {{Courier Bold} @Font any}},
{0.7 1.0} @Scale {{Courier Bold} @Font all} or whatever. If there isn't an {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field add
one.}
// @LVis listitem {If any other seddery or things used to happen to make the binary
control files use {{0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}}}{'s} variable substitution
features to achieve the same effect. Use {0.7 1.0} @Scale {{Courier Bold} @Font "debian/substvars"} if
you need to put "unusally-generated" information (apart from details of
{0.7 1.0} @Scale {{Courier Bold} @Font {.deb}} files) in the {0.7 1.0} @Scale {{Courier Bold} @Font {.changes}} file too.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 4}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.23" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.19" }
{"Edit/create" {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/control"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font Version} field. If it is generated unusually (not
equal to the source version) you must use the "-v" option to
"dpkg-gencontrol" (see below). {{0.7 1.0} @Scale {{Courier Bold} @Font Section}}, {{0.7 1.0} @Scale {{Courier Bold} @Font Priority}},
{0.7 1.0} @Scale {{Courier Bold} @Font Maintainer} go above the first blank line, most of the rest below.}
// @LVis listitem {Reorder the fields and add a blank line at an appropriate point,
separating the source package fields from the binary package
fields.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font Source} field.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font {"Standards"{--}"Version"}} field. The current value is
{{0.7 1.0} @Scale {{Courier Bold} @Font {0.2.0.0}}}.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field for each package to {{0.7 1.0} @Scale {{Courier Bold} @Font any}},
{0.7 1.0} @Scale {{Courier Bold} @Font all} or whatever. If there isn't an {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field add
one.}
// @LVis listitem {If any other seddery or things used to happen to make the binary
control files use {{0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}}}{'s} variable substitution
features to achieve the same effect. Use {0.7 1.0} @Scale {{Courier Bold} @Font "debian/substvars"} if
you need to put "unusally-generated" information (apart from details of
{0.7 1.0} @Scale {{Courier Bold} @Font {.deb}} files) in the {0.7 1.0} @Scale {{Courier Bold} @Font {.changes}} file too.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.policy.lout.23" }
{Add the {0.7 1.0} @Scale {{Courier Bold} @Font {"Standards"{--}"Version"}} field. The current value is
{{0.7 1.0} @Scale {{Courier Bold} @Font {0.2.0.0}}}.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.19" }
{"Edit/create" {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/control"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font Version} field. If it is generated unusually (not
equal to the source version) you must use the "-v" option to
"dpkg-gencontrol" (see below). {{0.7 1.0} @Scale {{Courier Bold} @Font Section}}, {{0.7 1.0} @Scale {{Courier Bold} @Font Priority}},
{0.7 1.0} @Scale {{Courier Bold} @Font Maintainer} go above the first blank line, most of the rest below.}
// @LVis listitem {Reorder the fields and add a blank line at an appropriate point,
separating the source package fields from the binary package
fields.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font Source} field.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font {"Standards"{--}"Version"}} field. The current value is
{{0.7 1.0} @Scale {{Courier Bold} @Font {0.2.0.0}}}.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field for each package to {{0.7 1.0} @Scale {{Courier Bold} @Font any}},
{0.7 1.0} @Scale {{Courier Bold} @Font all} or whatever. If there isn't an {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field add
one.}
// @LVis listitem {If any other seddery or things used to happen to make the binary
control files use {{0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}}}{'s} variable substitution
features to achieve the same effect. Use {0.7 1.0} @Scale {{Courier Bold} @Font "debian/substvars"} if
you need to put "unusally-generated" information (apart from details of
{0.7 1.0} @Scale {{Courier Bold} @Font {.deb}} files) in the {0.7 1.0} @Scale {{Courier Bold} @Font {.changes}} file too.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 5}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.24" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.19" }
{"Edit/create" {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/control"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font Version} field. If it is generated unusually (not
equal to the source version) you must use the "-v" option to
"dpkg-gencontrol" (see below). {{0.7 1.0} @Scale {{Courier Bold} @Font Section}}, {{0.7 1.0} @Scale {{Courier Bold} @Font Priority}},
{0.7 1.0} @Scale {{Courier Bold} @Font Maintainer} go above the first blank line, most of the rest below.}
// @LVis listitem {Reorder the fields and add a blank line at an appropriate point,
separating the source package fields from the binary package
fields.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font Source} field.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font {"Standards"{--}"Version"}} field. The current value is
{{0.7 1.0} @Scale {{Courier Bold} @Font {0.2.0.0}}}.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field for each package to {{0.7 1.0} @Scale {{Courier Bold} @Font any}},
{0.7 1.0} @Scale {{Courier Bold} @Font all} or whatever. If there isn't an {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field add
one.}
// @LVis listitem {If any other seddery or things used to happen to make the binary
control files use {{0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}}}{'s} variable substitution
features to achieve the same effect. Use {0.7 1.0} @Scale {{Courier Bold} @Font "debian/substvars"} if
you need to put "unusally-generated" information (apart from details of
{0.7 1.0} @Scale {{Courier Bold} @Font {.deb}} files) in the {0.7 1.0} @Scale {{Courier Bold} @Font {.changes}} file too.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.policy.lout.24" }
{Change the {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field for each package to {{0.7 1.0} @Scale {{Courier Bold} @Font any}},
{0.7 1.0} @Scale {{Courier Bold} @Font all} or whatever. If there isn't an {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field add
one.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.19" }
{"Edit/create" {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/control"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font Version} field. If it is generated unusually (not
equal to the source version) you must use the "-v" option to
"dpkg-gencontrol" (see below). {{0.7 1.0} @Scale {{Courier Bold} @Font Section}}, {{0.7 1.0} @Scale {{Courier Bold} @Font Priority}},
{0.7 1.0} @Scale {{Courier Bold} @Font Maintainer} go above the first blank line, most of the rest below.}
// @LVis listitem {Reorder the fields and add a blank line at an appropriate point,
separating the source package fields from the binary package
fields.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font Source} field.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font {"Standards"{--}"Version"}} field. The current value is
{{0.7 1.0} @Scale {{Courier Bold} @Font {0.2.0.0}}}.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field for each package to {{0.7 1.0} @Scale {{Courier Bold} @Font any}},
{0.7 1.0} @Scale {{Courier Bold} @Font all} or whatever. If there isn't an {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field add
one.}
// @LVis listitem {If any other seddery or things used to happen to make the binary
control files use {{0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}}}{'s} variable substitution
features to achieve the same effect. Use {0.7 1.0} @Scale {{Courier Bold} @Font "debian/substvars"} if
you need to put "unusally-generated" information (apart from details of
{0.7 1.0} @Scale {{Courier Bold} @Font {.deb}} files) in the {0.7 1.0} @Scale {{Courier Bold} @Font {.changes}} file too.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 6}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.25" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.19" }
{"Edit/create" {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/control"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font Version} field. If it is generated unusually (not
equal to the source version) you must use the "-v" option to
"dpkg-gencontrol" (see below). {{0.7 1.0} @Scale {{Courier Bold} @Font Section}}, {{0.7 1.0} @Scale {{Courier Bold} @Font Priority}},
{0.7 1.0} @Scale {{Courier Bold} @Font Maintainer} go above the first blank line, most of the rest below.}
// @LVis listitem {Reorder the fields and add a blank line at an appropriate point,
separating the source package fields from the binary package
fields.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font Source} field.}
// @LVis listitem {Add the {0.7 1.0} @Scale {{Courier Bold} @Font {"Standards"{--}"Version"}} field. The current value is
{{0.7 1.0} @Scale {{Courier Bold} @Font {0.2.0.0}}}.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field for each package to {{0.7 1.0} @Scale {{Courier Bold} @Font any}},
{0.7 1.0} @Scale {{Courier Bold} @Font all} or whatever. If there isn't an {0.7 1.0} @Scale {{Courier Bold} @Font Architecture} field add
one.}
// @LVis listitem {If any other seddery or things used to happen to make the binary
control files use {{0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}}}{'s} variable substitution
features to achieve the same effect. Use {0.7 1.0} @Scale {{Courier Bold} @Font "debian/substvars"} if
you need to put "unusally-generated" information (apart from details of
{0.7 1.0} @Scale {{Courier Bold} @Font {.deb}} files) in the {0.7 1.0} @Scale {{Courier Bold} @Font {.changes}} file too.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.policy.lout.25" }
{If any other seddery or things used to happen to make the binary
control files use {{0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}}}{'s} variable substitution
features to achieve the same effect. Use {0.7 1.0} @Scale {{Courier Bold} @Font "debian/substvars"} if
you need to put "unusally-generated" information (apart from details of
{0.7 1.0} @Scale {{Courier Bold} @Font {.deb}} files) in the {0.7 1.0} @Scale {{Courier Bold} @Font {.changes}} file too.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }}
{@LVis @MakeList 5}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.26" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.26" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.26" }
{Edit the {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font source} and {0.7 1.0} @Scale {{Courier Bold} @Font diff} and any {0.7 1.0} @Scale {{Courier Bold} @Font changes} and
{0.7 1.0} @Scale {{Courier Bold} @Font dist} targets. These things now happen in a "package-independent"
way and are not done by {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}.}
// @LVis listitem {Split the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target into {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}} and
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"indep"}}}; in many cases all of {0.7 1.0} @Scale {{Courier Bold} @Font binary} should go into
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}}}. Create the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target and the unused of
the two other {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"*"}} targets if there is one "-" you can copy
the ones from the {0.7 1.0} @Scale {{Courier Bold} @Font hello} package.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target to use {0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}} to make
the package control file(s). Move it to after all the files have been
installed but just before the last {0.7 1.0} @Scale {{Courier Bold} @Font chown} and {0.7 1.0} @Scale {{Courier Bold} @Font chmod} in
the target.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font {"debian"{--}"tmp"}} to {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/tmp"}}.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font "debian.{post,pre}{inst,rm}"} to
{{0.7 1.0} @Scale {{Courier Bold} @Font "debian/*"}}.}
// @LVis listitem {Remove the version number setting at the top, if there is one.}
// @LVis listitem {Ensure that the package's "Debian-specific" and upstream changelogs are
installed.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.27" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.26" }
{Edit the {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font source} and {0.7 1.0} @Scale {{Courier Bold} @Font diff} and any {0.7 1.0} @Scale {{Courier Bold} @Font changes} and
{0.7 1.0} @Scale {{Courier Bold} @Font dist} targets. These things now happen in a "package-independent"
way and are not done by {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}.}
// @LVis listitem {Split the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target into {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}} and
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"indep"}}}; in many cases all of {0.7 1.0} @Scale {{Courier Bold} @Font binary} should go into
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}}}. Create the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target and the unused of
the two other {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"*"}} targets if there is one "-" you can copy
the ones from the {0.7 1.0} @Scale {{Courier Bold} @Font hello} package.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target to use {0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}} to make
the package control file(s). Move it to after all the files have been
installed but just before the last {0.7 1.0} @Scale {{Courier Bold} @Font chown} and {0.7 1.0} @Scale {{Courier Bold} @Font chmod} in
the target.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font {"debian"{--}"tmp"}} to {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/tmp"}}.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font "debian.{post,pre}{inst,rm}"} to
{{0.7 1.0} @Scale {{Courier Bold} @Font "debian/*"}}.}
// @LVis listitem {Remove the version number setting at the top, if there is one.}
// @LVis listitem {Ensure that the package's "Debian-specific" and upstream changelogs are
installed.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.policy.lout.27" }
{Remove the {0.7 1.0} @Scale {{Courier Bold} @Font source} and {0.7 1.0} @Scale {{Courier Bold} @Font diff} and any {0.7 1.0} @Scale {{Courier Bold} @Font changes} and
{0.7 1.0} @Scale {{Courier Bold} @Font dist} targets. These things now happen in a "package-independent"
way and are not done by {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.26" }
{Edit the {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font source} and {0.7 1.0} @Scale {{Courier Bold} @Font diff} and any {0.7 1.0} @Scale {{Courier Bold} @Font changes} and
{0.7 1.0} @Scale {{Courier Bold} @Font dist} targets. These things now happen in a "package-independent"
way and are not done by {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}.}
// @LVis listitem {Split the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target into {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}} and
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"indep"}}}; in many cases all of {0.7 1.0} @Scale {{Courier Bold} @Font binary} should go into
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}}}. Create the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target and the unused of
the two other {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"*"}} targets if there is one "-" you can copy
the ones from the {0.7 1.0} @Scale {{Courier Bold} @Font hello} package.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target to use {0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}} to make
the package control file(s). Move it to after all the files have been
installed but just before the last {0.7 1.0} @Scale {{Courier Bold} @Font chown} and {0.7 1.0} @Scale {{Courier Bold} @Font chmod} in
the target.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font {"debian"{--}"tmp"}} to {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/tmp"}}.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font "debian.{post,pre}{inst,rm}"} to
{{0.7 1.0} @Scale {{Courier Bold} @Font "debian/*"}}.}
// @LVis listitem {Remove the version number setting at the top, if there is one.}
// @LVis listitem {Ensure that the package's "Debian-specific" and upstream changelogs are
installed.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.28" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.26" }
{Edit the {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font source} and {0.7 1.0} @Scale {{Courier Bold} @Font diff} and any {0.7 1.0} @Scale {{Courier Bold} @Font changes} and
{0.7 1.0} @Scale {{Courier Bold} @Font dist} targets. These things now happen in a "package-independent"
way and are not done by {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}.}
// @LVis listitem {Split the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target into {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}} and
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"indep"}}}; in many cases all of {0.7 1.0} @Scale {{Courier Bold} @Font binary} should go into
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}}}. Create the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target and the unused of
the two other {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"*"}} targets if there is one "-" you can copy
the ones from the {0.7 1.0} @Scale {{Courier Bold} @Font hello} package.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target to use {0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}} to make
the package control file(s). Move it to after all the files have been
installed but just before the last {0.7 1.0} @Scale {{Courier Bold} @Font chown} and {0.7 1.0} @Scale {{Courier Bold} @Font chmod} in
the target.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font {"debian"{--}"tmp"}} to {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/tmp"}}.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font "debian.{post,pre}{inst,rm}"} to
{{0.7 1.0} @Scale {{Courier Bold} @Font "debian/*"}}.}
// @LVis listitem {Remove the version number setting at the top, if there is one.}
// @LVis listitem {Ensure that the package's "Debian-specific" and upstream changelogs are
installed.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.policy.lout.28" }
{Split the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target into {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}} and
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"indep"}}}; in many cases all of {0.7 1.0} @Scale {{Courier Bold} @Font binary} should go into
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}}}. Create the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target and the unused of
the two other {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"*"}} targets if there is one "-" you can copy
the ones from the {0.7 1.0} @Scale {{Courier Bold} @Font hello} package.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.26" }
{Edit the {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font source} and {0.7 1.0} @Scale {{Courier Bold} @Font diff} and any {0.7 1.0} @Scale {{Courier Bold} @Font changes} and
{0.7 1.0} @Scale {{Courier Bold} @Font dist} targets. These things now happen in a "package-independent"
way and are not done by {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}.}
// @LVis listitem {Split the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target into {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}} and
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"indep"}}}; in many cases all of {0.7 1.0} @Scale {{Courier Bold} @Font binary} should go into
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}}}. Create the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target and the unused of
the two other {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"*"}} targets if there is one "-" you can copy
the ones from the {0.7 1.0} @Scale {{Courier Bold} @Font hello} package.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target to use {0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}} to make
the package control file(s). Move it to after all the files have been
installed but just before the last {0.7 1.0} @Scale {{Courier Bold} @Font chown} and {0.7 1.0} @Scale {{Courier Bold} @Font chmod} in
the target.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font {"debian"{--}"tmp"}} to {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/tmp"}}.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font "debian.{post,pre}{inst,rm}"} to
{{0.7 1.0} @Scale {{Courier Bold} @Font "debian/*"}}.}
// @LVis listitem {Remove the version number setting at the top, if there is one.}
// @LVis listitem {Ensure that the package's "Debian-specific" and upstream changelogs are
installed.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.29" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.26" }
{Edit the {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font source} and {0.7 1.0} @Scale {{Courier Bold} @Font diff} and any {0.7 1.0} @Scale {{Courier Bold} @Font changes} and
{0.7 1.0} @Scale {{Courier Bold} @Font dist} targets. These things now happen in a "package-independent"
way and are not done by {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}.}
// @LVis listitem {Split the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target into {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}} and
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"indep"}}}; in many cases all of {0.7 1.0} @Scale {{Courier Bold} @Font binary} should go into
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}}}. Create the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target and the unused of
the two other {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"*"}} targets if there is one "-" you can copy
the ones from the {0.7 1.0} @Scale {{Courier Bold} @Font hello} package.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target to use {0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}} to make
the package control file(s). Move it to after all the files have been
installed but just before the last {0.7 1.0} @Scale {{Courier Bold} @Font chown} and {0.7 1.0} @Scale {{Courier Bold} @Font chmod} in
the target.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font {"debian"{--}"tmp"}} to {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/tmp"}}.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font "debian.{post,pre}{inst,rm}"} to
{{0.7 1.0} @Scale {{Courier Bold} @Font "debian/*"}}.}
// @LVis listitem {Remove the version number setting at the top, if there is one.}
// @LVis listitem {Ensure that the package's "Debian-specific" and upstream changelogs are
installed.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.policy.lout.29" }
{Change the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target to use {0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}} to make
the package control file(s). Move it to after all the files have been
installed but just before the last {0.7 1.0} @Scale {{Courier Bold} @Font chown} and {0.7 1.0} @Scale {{Courier Bold} @Font chmod} in
the target.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.26" }
{Edit the {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font source} and {0.7 1.0} @Scale {{Courier Bold} @Font diff} and any {0.7 1.0} @Scale {{Courier Bold} @Font changes} and
{0.7 1.0} @Scale {{Courier Bold} @Font dist} targets. These things now happen in a "package-independent"
way and are not done by {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}.}
// @LVis listitem {Split the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target into {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}} and
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"indep"}}}; in many cases all of {0.7 1.0} @Scale {{Courier Bold} @Font binary} should go into
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}}}. Create the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target and the unused of
the two other {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"*"}} targets if there is one "-" you can copy
the ones from the {0.7 1.0} @Scale {{Courier Bold} @Font hello} package.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target to use {0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}} to make
the package control file(s). Move it to after all the files have been
installed but just before the last {0.7 1.0} @Scale {{Courier Bold} @Font chown} and {0.7 1.0} @Scale {{Courier Bold} @Font chmod} in
the target.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font {"debian"{--}"tmp"}} to {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/tmp"}}.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font "debian.{post,pre}{inst,rm}"} to
{{0.7 1.0} @Scale {{Courier Bold} @Font "debian/*"}}.}
// @LVis listitem {Remove the version number setting at the top, if there is one.}
// @LVis listitem {Ensure that the package's "Debian-specific" and upstream changelogs are
installed.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 4}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.30" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.26" }
{Edit the {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font source} and {0.7 1.0} @Scale {{Courier Bold} @Font diff} and any {0.7 1.0} @Scale {{Courier Bold} @Font changes} and
{0.7 1.0} @Scale {{Courier Bold} @Font dist} targets. These things now happen in a "package-independent"
way and are not done by {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}.}
// @LVis listitem {Split the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target into {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}} and
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"indep"}}}; in many cases all of {0.7 1.0} @Scale {{Courier Bold} @Font binary} should go into
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}}}. Create the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target and the unused of
the two other {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"*"}} targets if there is one "-" you can copy
the ones from the {0.7 1.0} @Scale {{Courier Bold} @Font hello} package.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target to use {0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}} to make
the package control file(s). Move it to after all the files have been
installed but just before the last {0.7 1.0} @Scale {{Courier Bold} @Font chown} and {0.7 1.0} @Scale {{Courier Bold} @Font chmod} in
the target.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font {"debian"{--}"tmp"}} to {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/tmp"}}.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font "debian.{post,pre}{inst,rm}"} to
{{0.7 1.0} @Scale {{Courier Bold} @Font "debian/*"}}.}
// @LVis listitem {Remove the version number setting at the top, if there is one.}
// @LVis listitem {Ensure that the package's "Debian-specific" and upstream changelogs are
installed.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.policy.lout.30" }
{Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font {"debian"{--}"tmp"}} to {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/tmp"}}.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.26" }
{Edit the {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font source} and {0.7 1.0} @Scale {{Courier Bold} @Font diff} and any {0.7 1.0} @Scale {{Courier Bold} @Font changes} and
{0.7 1.0} @Scale {{Courier Bold} @Font dist} targets. These things now happen in a "package-independent"
way and are not done by {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}.}
// @LVis listitem {Split the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target into {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}} and
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"indep"}}}; in many cases all of {0.7 1.0} @Scale {{Courier Bold} @Font binary} should go into
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}}}. Create the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target and the unused of
the two other {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"*"}} targets if there is one "-" you can copy
the ones from the {0.7 1.0} @Scale {{Courier Bold} @Font hello} package.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target to use {0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}} to make
the package control file(s). Move it to after all the files have been
installed but just before the last {0.7 1.0} @Scale {{Courier Bold} @Font chown} and {0.7 1.0} @Scale {{Courier Bold} @Font chmod} in
the target.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font {"debian"{--}"tmp"}} to {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/tmp"}}.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font "debian.{post,pre}{inst,rm}"} to
{{0.7 1.0} @Scale {{Courier Bold} @Font "debian/*"}}.}
// @LVis listitem {Remove the version number setting at the top, if there is one.}
// @LVis listitem {Ensure that the package's "Debian-specific" and upstream changelogs are
installed.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 5}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.31" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.26" }
{Edit the {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font source} and {0.7 1.0} @Scale {{Courier Bold} @Font diff} and any {0.7 1.0} @Scale {{Courier Bold} @Font changes} and
{0.7 1.0} @Scale {{Courier Bold} @Font dist} targets. These things now happen in a "package-independent"
way and are not done by {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}.}
// @LVis listitem {Split the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target into {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}} and
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"indep"}}}; in many cases all of {0.7 1.0} @Scale {{Courier Bold} @Font binary} should go into
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}}}. Create the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target and the unused of
the two other {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"*"}} targets if there is one "-" you can copy
the ones from the {0.7 1.0} @Scale {{Courier Bold} @Font hello} package.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target to use {0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}} to make
the package control file(s). Move it to after all the files have been
installed but just before the last {0.7 1.0} @Scale {{Courier Bold} @Font chown} and {0.7 1.0} @Scale {{Courier Bold} @Font chmod} in
the target.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font {"debian"{--}"tmp"}} to {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/tmp"}}.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font "debian.{post,pre}{inst,rm}"} to
{{0.7 1.0} @Scale {{Courier Bold} @Font "debian/*"}}.}
// @LVis listitem {Remove the version number setting at the top, if there is one.}
// @LVis listitem {Ensure that the package's "Debian-specific" and upstream changelogs are
installed.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.policy.lout.31" }
{Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font "debian.{post,pre}{inst,rm}"} to
{{0.7 1.0} @Scale {{Courier Bold} @Font "debian/*"}}.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.26" }
{Edit the {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font source} and {0.7 1.0} @Scale {{Courier Bold} @Font diff} and any {0.7 1.0} @Scale {{Courier Bold} @Font changes} and
{0.7 1.0} @Scale {{Courier Bold} @Font dist} targets. These things now happen in a "package-independent"
way and are not done by {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}.}
// @LVis listitem {Split the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target into {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}} and
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"indep"}}}; in many cases all of {0.7 1.0} @Scale {{Courier Bold} @Font binary} should go into
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}}}. Create the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target and the unused of
the two other {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"*"}} targets if there is one "-" you can copy
the ones from the {0.7 1.0} @Scale {{Courier Bold} @Font hello} package.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target to use {0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}} to make
the package control file(s). Move it to after all the files have been
installed but just before the last {0.7 1.0} @Scale {{Courier Bold} @Font chown} and {0.7 1.0} @Scale {{Courier Bold} @Font chmod} in
the target.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font {"debian"{--}"tmp"}} to {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/tmp"}}.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font "debian.{post,pre}{inst,rm}"} to
{{0.7 1.0} @Scale {{Courier Bold} @Font "debian/*"}}.}
// @LVis listitem {Remove the version number setting at the top, if there is one.}
// @LVis listitem {Ensure that the package's "Debian-specific" and upstream changelogs are
installed.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 6}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.32" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.26" }
{Edit the {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font source} and {0.7 1.0} @Scale {{Courier Bold} @Font diff} and any {0.7 1.0} @Scale {{Courier Bold} @Font changes} and
{0.7 1.0} @Scale {{Courier Bold} @Font dist} targets. These things now happen in a "package-independent"
way and are not done by {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}.}
// @LVis listitem {Split the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target into {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}} and
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"indep"}}}; in many cases all of {0.7 1.0} @Scale {{Courier Bold} @Font binary} should go into
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}}}. Create the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target and the unused of
the two other {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"*"}} targets if there is one "-" you can copy
the ones from the {0.7 1.0} @Scale {{Courier Bold} @Font hello} package.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target to use {0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}} to make
the package control file(s). Move it to after all the files have been
installed but just before the last {0.7 1.0} @Scale {{Courier Bold} @Font chown} and {0.7 1.0} @Scale {{Courier Bold} @Font chmod} in
the target.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font {"debian"{--}"tmp"}} to {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/tmp"}}.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font "debian.{post,pre}{inst,rm}"} to
{{0.7 1.0} @Scale {{Courier Bold} @Font "debian/*"}}.}
// @LVis listitem {Remove the version number setting at the top, if there is one.}
// @LVis listitem {Ensure that the package's "Debian-specific" and upstream changelogs are
installed.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.policy.lout.32" }
{Remove the version number setting at the top, if there is one.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.26" }
{Edit the {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font source} and {0.7 1.0} @Scale {{Courier Bold} @Font diff} and any {0.7 1.0} @Scale {{Courier Bold} @Font changes} and
{0.7 1.0} @Scale {{Courier Bold} @Font dist} targets. These things now happen in a "package-independent"
way and are not done by {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}.}
// @LVis listitem {Split the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target into {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}} and
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"indep"}}}; in many cases all of {0.7 1.0} @Scale {{Courier Bold} @Font binary} should go into
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}}}. Create the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target and the unused of
the two other {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"*"}} targets if there is one "-" you can copy
the ones from the {0.7 1.0} @Scale {{Courier Bold} @Font hello} package.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target to use {0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}} to make
the package control file(s). Move it to after all the files have been
installed but just before the last {0.7 1.0} @Scale {{Courier Bold} @Font chown} and {0.7 1.0} @Scale {{Courier Bold} @Font chmod} in
the target.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font {"debian"{--}"tmp"}} to {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/tmp"}}.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font "debian.{post,pre}{inst,rm}"} to
{{0.7 1.0} @Scale {{Courier Bold} @Font "debian/*"}}.}
// @LVis listitem {Remove the version number setting at the top, if there is one.}
// @LVis listitem {Ensure that the package's "Debian-specific" and upstream changelogs are
installed.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 7}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.33" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.26" }
{Edit the {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove the {0.7 1.0} @Scale {{Courier Bold} @Font source} and {0.7 1.0} @Scale {{Courier Bold} @Font diff} and any {0.7 1.0} @Scale {{Courier Bold} @Font changes} and
{0.7 1.0} @Scale {{Courier Bold} @Font dist} targets. These things now happen in a "package-independent"
way and are not done by {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}.}
// @LVis listitem {Split the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target into {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}} and
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"indep"}}}; in many cases all of {0.7 1.0} @Scale {{Courier Bold} @Font binary} should go into
{{0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"arch"}}}. Create the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target and the unused of
the two other {0.7 1.0} @Scale {{Courier Bold} @Font {"binary"{--}"*"}} targets if there is one "-" you can copy
the ones from the {0.7 1.0} @Scale {{Courier Bold} @Font hello} package.}
// @LVis listitem {Change the {0.7 1.0} @Scale {{Courier Bold} @Font binary} target to use {0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}} to make
the package control file(s). Move it to after all the files have been
installed but just before the last {0.7 1.0} @Scale {{Courier Bold} @Font chown} and {0.7 1.0} @Scale {{Courier Bold} @Font chmod} in
the target.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font {"debian"{--}"tmp"}} to {{0.7 1.0} @Scale {{Courier Bold} @Font "debian/tmp"}}.}
// @LVis listitem {Change occurrences of {0.7 1.0} @Scale {{Courier Bold} @Font "debian.{post,pre}{inst,rm}"} to
{{0.7 1.0} @Scale {{Courier Bold} @Font "debian/*"}}.}
// @LVis listitem {Remove the version number setting at the top, if there is one.}
// @LVis listitem {Ensure that the package's "Debian-specific" and upstream changelogs are
installed.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.policy.lout.33" }
{Ensure that the package's "Debian-specific" and upstream changelogs are
installed.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
25}
{@PageMarker
   @Tag { "582.policy.lout.25" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.policy.lout.33" }
   count { 0 }}
@LClos
}

{@OptGall {1 35 38 15 31 29 53 53 48 45 48 46 45 44 40 46 40 43 18 38
39 29 37 9 48 31}}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }}
{@LVis @MakeList 6}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.34" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.34" }
{Check that the {0.7 1.0} @Scale {{Courier Bold} @Font "debian/README"} is really the copyright file, and
if so rename it to {0.7 1.0} @Scale {{Courier Bold} @Font "debian/copyright"} and edit
{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"} to cope with this and to change the installation
of the copyright file from {0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}"/copyright"}}
instead of {{0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/copyright/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}}}}. If it isn't then
find {0.7 1.0} @Scale {{Courier Bold} @Font "debian/copyright"} and decide what to do with the
{{0.7 1.0} @Scale {{Courier Bold} @Font README}}.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }}
{@LVis @MakeList 7}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.35" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.35" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.35" }
{Check for various other anachronisms and problems:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove any {{0.7 1.0} @Scale {{Courier Bold} @Font Package_Revision}}, {0.7 1.0} @Scale {{Courier Bold} @Font {"Package"{--}"Revision"}} or
{0.7 1.0} @Scale {{Courier Bold} @Font Revision} fields.}
// @LVis listitem {Rename {0.7 1.0} @Scale {{Courier Bold} @Font Optional} to {{0.7 1.0} @Scale {{Courier Bold} @Font Suggests}}, {0.7 1.0} @Scale {{Courier Bold} @Font Recommended} to
{{0.7 1.0} @Scale {{Courier Bold} @Font Recommends}}.}
// @LVis listitem {Change {0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/examples/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}}} to
{{0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}"/examples"}}}.}
// @LVis listitem {Make sure that manpages are installed compressed.}
// @LVis listitem {Check that the description has an extended description, is
"well-formatted" and meaningful and helpful to people wanting to know
whether to install a package.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.36" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.35" }
{Check for various other anachronisms and problems:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove any {{0.7 1.0} @Scale {{Courier Bold} @Font Package_Revision}}, {0.7 1.0} @Scale {{Courier Bold} @Font {"Package"{--}"Revision"}} or
{0.7 1.0} @Scale {{Courier Bold} @Font Revision} fields.}
// @LVis listitem {Rename {0.7 1.0} @Scale {{Courier Bold} @Font Optional} to {{0.7 1.0} @Scale {{Courier Bold} @Font Suggests}}, {0.7 1.0} @Scale {{Courier Bold} @Font Recommended} to
{{0.7 1.0} @Scale {{Courier Bold} @Font Recommends}}.}
// @LVis listitem {Change {0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/examples/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}}} to
{{0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}"/examples"}}}.}
// @LVis listitem {Make sure that manpages are installed compressed.}
// @LVis listitem {Check that the description has an extended description, is
"well-formatted" and meaningful and helpful to people wanting to know
whether to install a package.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.policy.lout.36" }
{Remove any {{0.7 1.0} @Scale {{Courier Bold} @Font Package_Revision}}, {0.7 1.0} @Scale {{Courier Bold} @Font {"Package"{--}"Revision"}} or
{0.7 1.0} @Scale {{Courier Bold} @Font Revision} fields.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.35" }
{Check for various other anachronisms and problems:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove any {{0.7 1.0} @Scale {{Courier Bold} @Font Package_Revision}}, {0.7 1.0} @Scale {{Courier Bold} @Font {"Package"{--}"Revision"}} or
{0.7 1.0} @Scale {{Courier Bold} @Font Revision} fields.}
// @LVis listitem {Rename {0.7 1.0} @Scale {{Courier Bold} @Font Optional} to {{0.7 1.0} @Scale {{Courier Bold} @Font Suggests}}, {0.7 1.0} @Scale {{Courier Bold} @Font Recommended} to
{{0.7 1.0} @Scale {{Courier Bold} @Font Recommends}}.}
// @LVis listitem {Change {0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/examples/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}}} to
{{0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}"/examples"}}}.}
// @LVis listitem {Make sure that manpages are installed compressed.}
// @LVis listitem {Check that the description has an extended description, is
"well-formatted" and meaningful and helpful to people wanting to know
whether to install a package.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.37" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.35" }
{Check for various other anachronisms and problems:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove any {{0.7 1.0} @Scale {{Courier Bold} @Font Package_Revision}}, {0.7 1.0} @Scale {{Courier Bold} @Font {"Package"{--}"Revision"}} or
{0.7 1.0} @Scale {{Courier Bold} @Font Revision} fields.}
// @LVis listitem {Rename {0.7 1.0} @Scale {{Courier Bold} @Font Optional} to {{0.7 1.0} @Scale {{Courier Bold} @Font Suggests}}, {0.7 1.0} @Scale {{Courier Bold} @Font Recommended} to
{{0.7 1.0} @Scale {{Courier Bold} @Font Recommends}}.}
// @LVis listitem {Change {0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/examples/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}}} to
{{0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}"/examples"}}}.}
// @LVis listitem {Make sure that manpages are installed compressed.}
// @LVis listitem {Check that the description has an extended description, is
"well-formatted" and meaningful and helpful to people wanting to know
whether to install a package.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.policy.lout.37" }
{Rename {0.7 1.0} @Scale {{Courier Bold} @Font Optional} to {{0.7 1.0} @Scale {{Courier Bold} @Font Suggests}}, {0.7 1.0} @Scale {{Courier Bold} @Font Recommended} to
{{0.7 1.0} @Scale {{Courier Bold} @Font Recommends}}.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.35" }
{Check for various other anachronisms and problems:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove any {{0.7 1.0} @Scale {{Courier Bold} @Font Package_Revision}}, {0.7 1.0} @Scale {{Courier Bold} @Font {"Package"{--}"Revision"}} or
{0.7 1.0} @Scale {{Courier Bold} @Font Revision} fields.}
// @LVis listitem {Rename {0.7 1.0} @Scale {{Courier Bold} @Font Optional} to {{0.7 1.0} @Scale {{Courier Bold} @Font Suggests}}, {0.7 1.0} @Scale {{Courier Bold} @Font Recommended} to
{{0.7 1.0} @Scale {{Courier Bold} @Font Recommends}}.}
// @LVis listitem {Change {0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/examples/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}}} to
{{0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}"/examples"}}}.}
// @LVis listitem {Make sure that manpages are installed compressed.}
// @LVis listitem {Check that the description has an extended description, is
"well-formatted" and meaningful and helpful to people wanting to know
whether to install a package.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.38" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.35" }
{Check for various other anachronisms and problems:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove any {{0.7 1.0} @Scale {{Courier Bold} @Font Package_Revision}}, {0.7 1.0} @Scale {{Courier Bold} @Font {"Package"{--}"Revision"}} or
{0.7 1.0} @Scale {{Courier Bold} @Font Revision} fields.}
// @LVis listitem {Rename {0.7 1.0} @Scale {{Courier Bold} @Font Optional} to {{0.7 1.0} @Scale {{Courier Bold} @Font Suggests}}, {0.7 1.0} @Scale {{Courier Bold} @Font Recommended} to
{{0.7 1.0} @Scale {{Courier Bold} @Font Recommends}}.}
// @LVis listitem {Change {0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/examples/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}}} to
{{0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}"/examples"}}}.}
// @LVis listitem {Make sure that manpages are installed compressed.}
// @LVis listitem {Check that the description has an extended description, is
"well-formatted" and meaningful and helpful to people wanting to know
whether to install a package.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.policy.lout.38" }
{Change {0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/examples/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}}} to
{{0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}"/examples"}}}.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.35" }
{Check for various other anachronisms and problems:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove any {{0.7 1.0} @Scale {{Courier Bold} @Font Package_Revision}}, {0.7 1.0} @Scale {{Courier Bold} @Font {"Package"{--}"Revision"}} or
{0.7 1.0} @Scale {{Courier Bold} @Font Revision} fields.}
// @LVis listitem {Rename {0.7 1.0} @Scale {{Courier Bold} @Font Optional} to {{0.7 1.0} @Scale {{Courier Bold} @Font Suggests}}, {0.7 1.0} @Scale {{Courier Bold} @Font Recommended} to
{{0.7 1.0} @Scale {{Courier Bold} @Font Recommends}}.}
// @LVis listitem {Change {0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/examples/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}}} to
{{0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}"/examples"}}}.}
// @LVis listitem {Make sure that manpages are installed compressed.}
// @LVis listitem {Check that the description has an extended description, is
"well-formatted" and meaningful and helpful to people wanting to know
whether to install a package.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 4}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.39" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.35" }
{Check for various other anachronisms and problems:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove any {{0.7 1.0} @Scale {{Courier Bold} @Font Package_Revision}}, {0.7 1.0} @Scale {{Courier Bold} @Font {"Package"{--}"Revision"}} or
{0.7 1.0} @Scale {{Courier Bold} @Font Revision} fields.}
// @LVis listitem {Rename {0.7 1.0} @Scale {{Courier Bold} @Font Optional} to {{0.7 1.0} @Scale {{Courier Bold} @Font Suggests}}, {0.7 1.0} @Scale {{Courier Bold} @Font Recommended} to
{{0.7 1.0} @Scale {{Courier Bold} @Font Recommends}}.}
// @LVis listitem {Change {0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/examples/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}}} to
{{0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}"/examples"}}}.}
// @LVis listitem {Make sure that manpages are installed compressed.}
// @LVis listitem {Check that the description has an extended description, is
"well-formatted" and meaningful and helpful to people wanting to know
whether to install a package.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.policy.lout.39" }
{Make sure that manpages are installed compressed.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.35" }
{Check for various other anachronisms and problems:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove any {{0.7 1.0} @Scale {{Courier Bold} @Font Package_Revision}}, {0.7 1.0} @Scale {{Courier Bold} @Font {"Package"{--}"Revision"}} or
{0.7 1.0} @Scale {{Courier Bold} @Font Revision} fields.}
// @LVis listitem {Rename {0.7 1.0} @Scale {{Courier Bold} @Font Optional} to {{0.7 1.0} @Scale {{Courier Bold} @Font Suggests}}, {0.7 1.0} @Scale {{Courier Bold} @Font Recommended} to
{{0.7 1.0} @Scale {{Courier Bold} @Font Recommends}}.}
// @LVis listitem {Change {0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/examples/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}}} to
{{0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}"/examples"}}}.}
// @LVis listitem {Make sure that manpages are installed compressed.}
// @LVis listitem {Check that the description has an extended description, is
"well-formatted" and meaningful and helpful to people wanting to know
whether to install a package.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 5}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.40" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.35" }
{Check for various other anachronisms and problems:
//{1.0vx} @RawList
   style { @Bullet }
   gap { 1.0vx }
// @LVis listitem {Remove any {{0.7 1.0} @Scale {{Courier Bold} @Font Package_Revision}}, {0.7 1.0} @Scale {{Courier Bold} @Font {"Package"{--}"Revision"}} or
{0.7 1.0} @Scale {{Courier Bold} @Font Revision} fields.}
// @LVis listitem {Rename {0.7 1.0} @Scale {{Courier Bold} @Font Optional} to {{0.7 1.0} @Scale {{Courier Bold} @Font Suggests}}, {0.7 1.0} @Scale {{Courier Bold} @Font Recommended} to
{{0.7 1.0} @Scale {{Courier Bold} @Font Recommends}}.}
// @LVis listitem {Change {0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/examples/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}}} to
{{0.7 1.0} @Scale {{Courier Bold} @Font {"/usr/doc/"{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}"/examples"}}}.}
// @LVis listitem {Make sure that manpages are installed compressed.}
// @LVis listitem {Check that the description has an extended description, is
"well-formatted" and meaningful and helpful to people wanting to know
whether to install a package.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.policy.lout.40" }
{Check that the description has an extended description, is
"well-formatted" and meaningful and helpful to people wanting to know
whether to install a package.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }}
{@LVis @MakeList 8}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.41" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.41" }
{Look everything over.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }}
{@LVis @MakeList 9}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.42" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.42" }
{Do a test build using {{0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"buildpackage" ""{--}"ur" ""{--}"uc" {""{--}"r"}{{1.4285714285 1.0} @Scale {{Times Slope} @Font whatever}}}}}.
Check the permissions and locations of files in the resulting package
by eyeballing the output of {{0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"deb" ""{--}""{--}"contents"}}}, and check that
the source build happened OK. Test install the binary package(s) and
test extract the source package(s).}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }}
{@LVis @MakeList 10}
{@LVis @NumberMarker
   @Tag { "1306.policy.lout.43" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.policy.lout.43" }
{Sign the release: either "re-run" {0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"buildpackage"}} (this will
rebuild the package entirely), or "PGP-sign" the {{0.7 1.0} @Scale {{Courier Bold} @Font {.dsc}}}, rebuild the
{0.7 1.0} @Scale {{Courier Bold} @Font {.changes}} using {{0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"genchanges"}}}, and then "PGP-sign" the
{{0.7 1.0} @Scale {{Courier Bold} @Font {.changes}}}.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{NonStart @Runner
   @Tag { "1954.policy.lout.4" }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{NonStart @Runner
   @Tag { "1954.policy.lout.2" }}
@LClos
}

