{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginTheoremCounter {}}
{@LVis @TheoremCounterMarker
   @Tag { "3278.programmer.lout.1" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginDefinitionCounter {}}
{@LVis @DefinitionCounterMarker
   @Tag { "3336.programmer.lout.1" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginClaimCounter {}}
{@LVis @ClaimCounterMarker
   @Tag { "3391.programmer.lout.1" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginPropositionCounter {}}
{@LVis @PropositionCounterMarker
   @Tag { "3445.programmer.lout.1" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginLemmaCounter {}}
{@LVis @LemmaCounterMarker
   @Tag { "3500.programmer.lout.1" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginCorollaryCounter {}}
{@LVis @CorollaryCounterMarker
   @Tag { "3554.programmer.lout.1" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginExampleCounter {}}
{@LVis @ExampleCounterMarker
   @Tag { "3609.programmer.lout.1" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{Yes @LVis @BeginDisplayCounter {}}
@LEnv
{@LUse @DocumentLayout}
{Yes @LVis @BeginDisplayCounter {}}
{?? @LVis @Then ??}
{@LVis y}
@LClos
{@LVis @NumDispCounterMarker
   @Tag { "1400.programmer.lout.1" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FigurePrefixMarker
   @Tag { "4153.programmer.lout.1" }
   prefix {  }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FigureCounterMarker
   @Tag { "4161.programmer.lout.1" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @TablePrefixMarker
   @Tag { "4334.programmer.lout.1" }
   prefix {  }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @TableCounterMarker
   @Tag { "4342.programmer.lout.1" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginDefinitionCounter {}}
{@LVis @DefinitionCounterMarker
   @Tag { "3336.programmer.lout.2" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginClaimCounter {}}
{@LVis @ClaimCounterMarker
   @Tag { "3391.programmer.lout.2" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginPropositionCounter {}}
{@LVis @PropositionCounterMarker
   @Tag { "3445.programmer.lout.2" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginLemmaCounter {}}
{@LVis @LemmaCounterMarker
   @Tag { "3500.programmer.lout.2" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginCorollaryCounter {}}
{@LVis @CorollaryCounterMarker
   @Tag { "3554.programmer.lout.2" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @BeginExampleCounter {}}
{@LVis @ExampleCounterMarker
   @Tag { "3609.programmer.lout.2" }
   val { @LVis prefix @DotJoin 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @PageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
   extra { Yes }
1}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
   extra { Yes }
   @AtTop { @LVis @AtTop }
1}
{@PageMarker
   @Tag { "582.programmer.lout.1" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.1" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{Start @Runner
   @Tag { "1954.programmer.lout.3" }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @PageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
   extra { Yes }
1}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
   extra { Yes }
   @AtTop { @LVis @AtTop }
1}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
2}
{@PageMarker
   @Tag { "582.programmer.lout.2" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.2" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
3}
{@PageMarker
   @Tag { "582.programmer.lout.3" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.3" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.programmer.lout.1" }
{{0.7 1.0} @Scale {{Courier Bold} @Font dpkg}
is targetted primarily at Debian "GNU/Linux," but may work on or be
ported to other systems.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.1"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.4" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.1"}
{@LVis @NumberMarker
   @Tag { "2521.programmer.lout.1" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
3}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
4}
{@PageMarker
   @Tag { "582.programmer.lout.4" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.5" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
5}
{@PageMarker
   @Tag { "582.programmer.lout.5" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.6" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis @Disp ??}
{@LVis x}
@LClos
{@FootNote
   @Tag { "2521.programmer.lout.2" }
{That
means that if it runs successfully or fails and then you call it again
it doesn't bomb out, but just ensures that everything is the way it
ought to be.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.2"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.7" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.2"}
{@LVis @NumberMarker
   @Tag { "2521.programmer.lout.2" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
5}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
6}
{@PageMarker
   @Tag { "582.programmer.lout.6" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.8" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.1" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.1" }
{{0.7 1.0} @Scale {{Courier Bold} @Font Package} (mandatory)}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.2" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.2" }
{{0.7 1.0} @Scale {{Courier Bold} @Font Version} (mandatory)}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.3" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.3" }
{{0.7 1.0} @Scale {{Courier Bold} @Font Architecture}
{(mandatory)}{@FootNote {This field should appear in all packages, though
{0.7 1.0} @Scale {{Courier Bold} @Font dpkg} doesn't require it yet so that old packages can still be
installed.}}}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.3" }
{{0.7 1.0} @Scale {{Courier Bold} @Font Architecture}
{(mandatory)}{@FootNote {This field should appear in all packages, though
{0.7 1.0} @Scale {{Courier Bold} @Font dpkg} doesn't require it yet so that old packages can still be
installed.}}}}
{@LVis x}
@LClos
{@FootNote
   @Tag { "2521.programmer.lout.3" }
{This field should appear in all packages, though
{0.7 1.0} @Scale {{Courier Bold} @Font dpkg} doesn't require it yet so that old packages can still be
installed.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 4}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.4" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.4" }
{{{0.7 1.0} @Scale {{Courier Bold} @Font Depends}}, {0.7 1.0} @Scale {{Courier Bold} @Font Provides} et al.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 5}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.5" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.5" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 6}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.6" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.6" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 7}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.7" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.7" }
{{{0.7 1.0} @Scale {{Courier Bold} @Font Section}}, {0.7 1.0} @Scale {{Courier Bold} @Font Priority}}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 8}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.8" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.8" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 9}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.9" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.9" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 10}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.10" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.10" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.3"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.9" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.3"}
{@LVis @NumberMarker
   @Tag { "2521.programmer.lout.3" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
7}
{@PageMarker
   @Tag { "582.programmer.lout.7" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.10" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
7}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
8}
{@PageMarker
   @Tag { "582.programmer.lout.8" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.11" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.programmer.lout.4" }
{This is so that the control file which is
produced has the right permissions}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.programmer.lout.5" }
{They may be specified either
in the locations in the source tree where they are created or in the
locations in the temporary build tree where they are installed prior
to binary package creation.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.4"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.12" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.4"}
{@LVis @NumberMarker
   @Tag { "2521.programmer.lout.4" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.5"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.13" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.5"}
{@LVis @NumberMarker
   @Tag { "2521.programmer.lout.5" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
9}
{@PageMarker
   @Tag { "582.programmer.lout.9" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.14" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
9}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
10}
{@PageMarker
   @Tag { "582.programmer.lout.10" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.15" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
11}
{@PageMarker
   @Tag { "582.programmer.lout.11" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.16" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.11" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.11" }
{{0.7 1.0} @Scale {{Courier Bold} @Font Source} (mandatory)}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.12" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.12" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.13" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.13" }
{{0.7 1.0} @Scale {{Courier Bold} @Font Section} and {0.7 1.0} @Scale {{Courier Bold} @Font Priority}
(classification, mandatory)}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 4}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.14" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.14" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
11}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
12}
{@PageMarker
   @Tag { "582.programmer.lout.12" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.17" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.15" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.15" }
{{0.7 1.0} @Scale {{Courier Bold} @Font Package} (mandatory)}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.16" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.16" }
{{0.7 1.0} @Scale {{Courier Bold} @Font Architecture} (mandatory)}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.17" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.17" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 4}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.18" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.18" }
{{0.7 1.0} @Scale {{Courier Bold} @Font Section} and {0.7 1.0} @Scale {{Courier Bold} @Font Priority} (classification)}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 5}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.19" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.19" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 6}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.20" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.20" }
{{0.7 1.0} @Scale {{Courier Bold} @Font Depends} et al. (package interrelationships)}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.programmer.lout.6" }
{Though there is nothing stopping an author who is
also the Debian maintainer from using it for all their changes, it
will have to be renamed if the Debian and upstream maintainers become
different people.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.6"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.18" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.6"}
{@LVis @NumberMarker
   @Tag { "2521.programmer.lout.6" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
13}
{@PageMarker
   @Tag { "582.programmer.lout.13" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.19" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
13}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
14}
{@PageMarker
   @Tag { "582.programmer.lout.14" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.20" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.21" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.21" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.22" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.22" }
{{0.7 1.0} @Scale {{Courier Bold} @Font Version} (mandatory)}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.23" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.23" }
{{0.7 1.0} @Scale {{Courier Bold} @Font Distribution} (mandatory)}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 4}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.24" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.24" }
{{0.7 1.0} @Scale {{Courier Bold} @Font Urgency} (mandatory)}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 5}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.25" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.25" }
{{0.7 1.0} @Scale {{Courier Bold} @Font Maintainer} (mandatory)}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 6}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.26" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.26" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 7}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.27" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.27" }
{{0.7 1.0} @Scale {{Courier Bold} @Font Changes} (mandatory)}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
15}
{@PageMarker
   @Tag { "582.programmer.lout.15" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.21" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.programmer.lout.7" }
{{0.7 1.0} @Scale {{Courier Bold} @Font {files.new}} is used as a temporary file by
{0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"gencontrol"}} and {0.7 1.0} @Scale {{Courier Bold} @Font {"dpkg"{--}"distaddfile"}} "-" they write a new
version of {0.7 1.0} @Scale {{Courier Bold} @Font files} here before renaming it, to avoid leaving a
corrupted copy if an error occurs}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis @Disp ??}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.28" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis @Disp ??}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.programmer.lout.28" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis @Disp ??}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.29" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis @Disp ??}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.programmer.lout.29" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis @Disp ??}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.30" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis @Disp ??}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.programmer.lout.30" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis @Disp ??}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 4}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.31" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis @Disp ??}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.programmer.lout.31" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis @Disp ??}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 5}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.32" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis @Disp ??}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.programmer.lout.32" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis @Disp ??}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 6}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.33" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis @Disp ??}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.programmer.lout.33" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis @Disp ??}
{@LVis x}
@LClos
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 7}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.34" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis @Disp ??}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.programmer.lout.34" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.7"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.22" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.7"}
{@LVis @NumberMarker
   @Tag { "2521.programmer.lout.7" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
15}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
16}
{@PageMarker
   @Tag { "582.programmer.lout.16" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.23" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }
   gap { 1.0vx }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.35" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.35" }
{Untar the tarfile, which will create a {0.7 1.0} @Scale {{Courier Bold} @Font {.orig}} directory.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }
   gap { 1.0vx }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.36" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.36" }
{Rename the {0.7 1.0} @Scale {{Courier Bold} @Font {.orig}} directory to
{{0.7 1.0} @Scale {{Courier Bold} @Font {{{1.4285714285 1.0} @Scale {{Times Slope} @Font package}}{""{--}""}{{1.4285714285 1.0} @Scale {{Times Slope} @Font version}}}}}.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }
   gap { 1.0vx }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.37" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.37" }
{Create the subdirectory {0.7 1.0} @Scale {{Courier Bold} @Font debian} at the top of the source
tree.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }
   gap { 1.0vx }}
{@LVis @MakeList 4}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.38" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.38" }
{Apply the diff using {{0.7 1.0} @Scale {{Courier Bold} @Font {patch ""{--}"p0"}}}.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }
   gap { 1.0vx }}
{@LVis @MakeList 5}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.39" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.39" }
{Untar the tarfile again if you want a copy of the original
source code alongside the Debianised version.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.programmer.lout.8" }
{Setgid directories are
allowed.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.40" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.40" }
{Adding or removing symbolic links, sockets or pipes.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.41" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.41" }
{Changing the targets of symbolic links.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.42" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.42" }
{Creating directories, other than {{0.7 1.0} @Scale {{Courier Bold} @Font debian}}.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 4}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.43" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.43" }
{Changes to the contents of binary files.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.8"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.24" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.8"}
{@LVis @NumberMarker
   @Tag { "2521.programmer.lout.8" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
17}
{@PageMarker
   @Tag { "582.programmer.lout.17" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.25" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.44" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.44" }
{Removing files, directories or symlinks. @FootNote {Renaming a
file is not treated specially "-" it is seen as the removal of the old
file (which generates a warning, but is otherwise ignored), and the
creation of the new one.}}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.44" }
{Removing files, directories or symlinks. @FootNote {Renaming a
file is not treated specially "-" it is seen as the removal of the old
file (which generates a warning, but is otherwise ignored), and the
creation of the new one.}}}
{@LVis x}
@LClos
{@FootNote
   @Tag { "2521.programmer.lout.9" }
{Renaming a
file is not treated specially "-" it is seen as the removal of the old
file (which generates a warning, but is otherwise ignored), and the
creation of the new one.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.45" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.45" }
{Changing the permissions of files (other than
{{0.7 1.0} @Scale {{Courier Bold} @Font "debian/rules"}}) and directories.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.9"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.26" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.9"}
{@LVis @NumberMarker
   @Tag { "2521.programmer.lout.9" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
17}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
18}
{@PageMarker
   @Tag { "582.programmer.lout.18" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.27" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.programmer.lout.10" }
{The characters {0.7 1.0} @Scale {{Courier Bold} @Font "@"} {0.7 1.0} @Scale {{Courier Bold} @Font :} {0.7 1.0} @Scale {{Courier Bold} @Font =} {0.7 1.0} @Scale {{Courier Bold} @Font %} {0.7 1.0} @Scale {{Courier Bold} @Font _} (at,
colon, equals, percent and underscore) used to be legal and are still
accepted when found in a package file, but may not be used in new
packages}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.10"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.28" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.10"}
{@LVis @NumberMarker
   @Tag { "2521.programmer.lout.10" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
19}
{@PageMarker
   @Tag { "582.programmer.lout.19" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.29" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.programmer.lout.11" }
{This is a bug.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.programmer.lout.12" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.11"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.30" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.11"}
{@LVis @NumberMarker
   @Tag { "2521.programmer.lout.11" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.12"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.31" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.12"}
{@LVis @NumberMarker
   @Tag { "2521.programmer.lout.12" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
19}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
20}
{@PageMarker
   @Tag { "582.programmer.lout.20" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.32" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.programmer.lout.13" }
{It is
usual to leave a space after the package name if a version number is
specified.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.13"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.33" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.13"}
{@LVis @NumberMarker
   @Tag { "2521.programmer.lout.13" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
21}
{@PageMarker
   @Tag { "582.programmer.lout.21" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.34" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.programmer.lout.14" }
{A space after each comma is conventional.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.programmer.lout.15" }
{That is, the parts which are not the
{{0.7 1.0} @Scale {{Courier Bold} @Font {.dsc}}}.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.14"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.35" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.14"}
{@LVis @NumberMarker
   @Tag { "2521.programmer.lout.14" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.15"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.36" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.15"}
{@LVis @NumberMarker
   @Tag { "2521.programmer.lout.15" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
21}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
22}
{@PageMarker
   @Tag { "582.programmer.lout.22" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.37" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
23}
{@PageMarker
   @Tag { "582.programmer.lout.23" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.38" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
23}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
24}
{@PageMarker
   @Tag { "582.programmer.lout.24" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.39" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
25}
{@PageMarker
   @Tag { "582.programmer.lout.25" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.40" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
25}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
26}
{@PageMarker
   @Tag { "582.programmer.lout.26" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.41" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
27}
{@PageMarker
   @Tag { "582.programmer.lout.27" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.42" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.46" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.46" }
{{Times Slope} @Font "new-preinst" {0.7 1.0} @Scale {{Courier Bold} @Font install}}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.47" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.47" }
{{Times Slope} @Font "new-preinst" {0.7 1.0} @Scale {{Courier Bold} @Font install} {Times Slope} @Font "old-version"}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.48" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.48" }
{{Times Slope} @Font "new-preinst" {0.7 1.0} @Scale {{Courier Bold} @Font upgrade} {Times Slope} @Font "old-version"}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 4}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.49" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.49" }
{{Times Slope} @Font "old-preinst" {0.7 1.0} @Scale {{Courier Bold} @Font {"abort"{--}"upgrade"}} {Times Slope} @Font "new-version"}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.50" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.50" }
{{Times Slope} @Font postinst {0.7 1.0} @Scale {{Courier Bold} @Font configure} {Times Slope} @Font "most-recently-configured-version"}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.51" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.51" }
{{Times Slope} @Font "old-postinst" {0.7 1.0} @Scale {{Courier Bold} @Font {"abort"{--}"upgrade"}} {Times Slope} @Font {new version}}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.52" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.52" }
{{Times Slope} @Font "conflictor's-postinst" {0.7 1.0} @Scale {{Courier Bold} @Font {"abort"{--}"remove"}}
 {0.7 1.0} @Scale {{Courier Bold} @Font {"in"{--}"favour"}} {Times Slope} @Font package {Times Slope} @Font "new-version"}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 4}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.53" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.53" }
{{Times Slope} @Font "deconfigured's-postinst" {0.7 1.0} @Scale {{Courier Bold} @Font {"abort"{--}"deconfigure"}}
 {0.7 1.0} @Scale {{Courier Bold} @Font {"in"{--}"favour"}} {Times Slope} @Font "failed-install-package" {Times Slope} @Font version
 {0.7 1.0} @Scale {{Courier Bold} @Font removing} {Times Slope} @Font "conflicting-package" {Times Slope} @Font version}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.54" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.54" }
{{Times Slope} @Font prerm {0.7 1.0} @Scale {{Courier Bold} @Font remove}}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.55" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.55" }
{{Times Slope} @Font "old-prerm" {0.7 1.0} @Scale {{Courier Bold} @Font upgrade} {Times Slope} @Font "new-version"}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.56" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.56" }
{{Times Slope} @Font "new-prerm" {0.7 1.0} @Scale {{Courier Bold} @Font {"failed"{--}"upgrade"}} {Times Slope} @Font "old-version"}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 4}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.57" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.57" }
{{Times Slope} @Font "conflictor's-prerm" {0.7 1.0} @Scale {{Courier Bold} @Font remove} {0.7 1.0} @Scale {{Courier Bold} @Font {"in"{--}"favour"}}
 {Times Slope} @Font package {Times Slope} @Font "new-version"}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
27}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
28}
{@PageMarker
   @Tag { "582.programmer.lout.28" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.43" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 5}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.58" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.58" }
{{Times Slope} @Font "deconfigured's-prerm" {0.7 1.0} @Scale {{Courier Bold} @Font deconfigure}
 {0.7 1.0} @Scale {{Courier Bold} @Font {"in"{--}"favour"}} {Times Slope} @Font "package-being-installed" {Times Slope} @Font version
 {0.7 1.0} @Scale {{Courier Bold} @Font removing} {Times Slope} @Font "conflicting-package" {Times Slope} @Font version}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.59" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.59" }
{{Times Slope} @Font postrm {0.7 1.0} @Scale {{Courier Bold} @Font remove}}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.60" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.60" }
{{Times Slope} @Font postrm {0.7 1.0} @Scale {{Courier Bold} @Font purge}}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.61" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.61" }
{{Times Slope} @Font "old-postrm" {0.7 1.0} @Scale {{Courier Bold} @Font upgrade} {Times Slope} @Font "new-version"}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 4}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.62" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.62" }
{{Times Slope} @Font "new-postrm" {0.7 1.0} @Scale {{Courier Bold} @Font {"failed"{--}"upgrade"}} {Times Slope} @Font "old-version"}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 5}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.63" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.63" }
{{Times Slope} @Font "new-postrm" {0.7 1.0} @Scale {{Courier Bold} @Font {"abort"{--}"install"}}}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 6}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.64" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.64" }
{{Times Slope} @Font "new-postrm" {0.7 1.0} @Scale {{Courier Bold} @Font {"abort"{--}"install"}} {Times Slope} @Font "old-version"}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 7}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.65" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.65" }
{{Times Slope} @Font "new-postrm" {0.7 1.0} @Scale {{Courier Bold} @Font {"abort"{--}"upgrade"}} {Times Slope} @Font "old-version"}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 8}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.66" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.66" }
{{Times Slope} @Font "disappearer's-postrm" {0.7 1.0} @Scale {{Courier Bold} @Font disappear} {Times Slope} @Font overwriter {Times Slope} @Font "new-version"}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.69" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.67" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.67" }
{@RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {If a version the package is already
installed, call
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"prerm"}} upgrade {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {If this gives an error (ie, a "non-zero" exit status), dpkg will
attempt instead:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"prerm"}} "failed"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} Error unwind, for both the above cases:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"postinst"}} "abort"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { {@Roman&&{num}}. }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.68" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.67" }
{@RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {If a version the package is already
installed, call
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"prerm"}} upgrade {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {If this gives an error (ie, a "non-zero" exit status), dpkg will
attempt instead:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"prerm"}} "failed"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} Error unwind, for both the above cases:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"postinst"}} "abort"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.programmer.lout.68" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.67" }
{@RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {If a version the package is already
installed, call
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"prerm"}} upgrade {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {If this gives an error (ie, a "non-zero" exit status), dpkg will
attempt instead:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"prerm"}} "failed"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} Error unwind, for both the above cases:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"postinst"}} "abort"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { {@Roman&&{num}}. }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.70" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.67" }
{@RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {If a version the package is already
installed, call
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"prerm"}} upgrade {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {If this gives an error (ie, a "non-zero" exit status), dpkg will
attempt instead:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"prerm"}} "failed"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} Error unwind, for both the above cases:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"postinst"}} "abort"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.programmer.lout.69" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.71" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.70" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.70" }
{If a `conflicting' package is being removed at the same time:
//{@ParaGap} @RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {If any packages depended on that conflicting package and
{0.7 1.0} @Scale {{Courier Bold} @Font {""{--}""{--}"auto"{--}"deconfigure"}} is specified, call, for each such package:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"deconfigured's"{--}"prerm"}} deconfigure "\\"
    "in"{--}"favour" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"package"{--}"being"{--}"installed"}} {1.4285714285 1.0} @Scale {{Times Slope} @Font version} "\\"
    removing {1.4285714285 1.0} @Scale {{Times Slope} @Font {"conflicting"{--}"package"}} {1.4285714285 1.0} @Scale {{Times Slope} @Font version}}}}}
//{0.2fe} Error unwind:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"deconfigured's"{--}"postinst"}} "abort"{--}"deconfigure" "\\"
    "in"{--}"favour" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"package"{--}"being"{--}"installed"{--}"but"{--}"failed"}} {1.4285714285 1.0} @Scale {{Times Slope} @Font version} "\\"
    removing {1.4285714285 1.0} @Scale {{Times Slope} @Font {"conflicting"{--}"package"}} {1.4285714285 1.0} @Scale {{Times Slope} @Font version}}}}}
//{0.2fe} The deconfigured packages are marked as requiring configuration, so
that if {0.7 1.0} @Scale {{Courier Bold} @Font {""{--}""{--}"install"}} is used they will be configured again if
possible.}
// @LVis listitem {To prepare for removal of the conflicting package, call:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"conflictor's"{--}"prerm"}} remove "in"{--}"favour" {1.4285714285 1.0} @Scale {{Times Slope} @Font package} {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} Error unwind:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"conflictor's"{--}"postinst"}} "abort"{--}"remove" "\\"
    "in"{--}"favour" {1.4285714285 1.0} @Scale {{Times Slope} @Font package} {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { {@Roman&&{num}}. }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.72" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.70" }
{If a `conflicting' package is being removed at the same time:
//{@ParaGap} @RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {If any packages depended on that conflicting package and
{0.7 1.0} @Scale {{Courier Bold} @Font {""{--}""{--}"auto"{--}"deconfigure"}} is specified, call, for each such package:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"deconfigured's"{--}"prerm"}} deconfigure "\\"
    "in"{--}"favour" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"package"{--}"being"{--}"installed"}} {1.4285714285 1.0} @Scale {{Times Slope} @Font version} "\\"
    removing {1.4285714285 1.0} @Scale {{Times Slope} @Font {"conflicting"{--}"package"}} {1.4285714285 1.0} @Scale {{Times Slope} @Font version}}}}}
//{0.2fe} Error unwind:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"deconfigured's"{--}"postinst"}} "abort"{--}"deconfigure" "\\"
    "in"{--}"favour" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"package"{--}"being"{--}"installed"{--}"but"{--}"failed"}} {1.4285714285 1.0} @Scale {{Times Slope} @Font version} "\\"
    removing {1.4285714285 1.0} @Scale {{Times Slope} @Font {"conflicting"{--}"package"}} {1.4285714285 1.0} @Scale {{Times Slope} @Font version}}}}}
//{0.2fe} The deconfigured packages are marked as requiring configuration, so
that if {0.7 1.0} @Scale {{Courier Bold} @Font {""{--}""{--}"install"}} is used they will be configured again if
possible.}
// @LVis listitem {To prepare for removal of the conflicting package, call:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"conflictor's"{--}"prerm"}} remove "in"{--}"favour" {1.4285714285 1.0} @Scale {{Times Slope} @Font package} {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} Error unwind:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"conflictor's"{--}"postinst"}} "abort"{--}"remove" "\\"
    "in"{--}"favour" {1.4285714285 1.0} @Scale {{Times Slope} @Font package} {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.programmer.lout.71" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.70" }
{If a `conflicting' package is being removed at the same time:
//{@ParaGap} @RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {If any packages depended on that conflicting package and
{0.7 1.0} @Scale {{Courier Bold} @Font {""{--}""{--}"auto"{--}"deconfigure"}} is specified, call, for each such package:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"deconfigured's"{--}"prerm"}} deconfigure "\\"
    "in"{--}"favour" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"package"{--}"being"{--}"installed"}} {1.4285714285 1.0} @Scale {{Times Slope} @Font version} "\\"
    removing {1.4285714285 1.0} @Scale {{Times Slope} @Font {"conflicting"{--}"package"}} {1.4285714285 1.0} @Scale {{Times Slope} @Font version}}}}}
//{0.2fe} Error unwind:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"deconfigured's"{--}"postinst"}} "abort"{--}"deconfigure" "\\"
    "in"{--}"favour" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"package"{--}"being"{--}"installed"{--}"but"{--}"failed"}} {1.4285714285 1.0} @Scale {{Times Slope} @Font version} "\\"
    removing {1.4285714285 1.0} @Scale {{Times Slope} @Font {"conflicting"{--}"package"}} {1.4285714285 1.0} @Scale {{Times Slope} @Font version}}}}}
//{0.2fe} The deconfigured packages are marked as requiring configuration, so
that if {0.7 1.0} @Scale {{Courier Bold} @Font {""{--}""{--}"install"}} is used they will be configured again if
possible.}
// @LVis listitem {To prepare for removal of the conflicting package, call:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"conflictor's"{--}"prerm"}} remove "in"{--}"favour" {1.4285714285 1.0} @Scale {{Times Slope} @Font package} {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} Error unwind:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"conflictor's"{--}"postinst"}} "abort"{--}"remove" "\\"
    "in"{--}"favour" {1.4285714285 1.0} @Scale {{Times Slope} @Font package} {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { {@Roman&&{num}}. }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.73" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.70" }
{If a `conflicting' package is being removed at the same time:
//{@ParaGap} @RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {If any packages depended on that conflicting package and
{0.7 1.0} @Scale {{Courier Bold} @Font {""{--}""{--}"auto"{--}"deconfigure"}} is specified, call, for each such package:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"deconfigured's"{--}"prerm"}} deconfigure "\\"
    "in"{--}"favour" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"package"{--}"being"{--}"installed"}} {1.4285714285 1.0} @Scale {{Times Slope} @Font version} "\\"
    removing {1.4285714285 1.0} @Scale {{Times Slope} @Font {"conflicting"{--}"package"}} {1.4285714285 1.0} @Scale {{Times Slope} @Font version}}}}}
//{0.2fe} Error unwind:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"deconfigured's"{--}"postinst"}} "abort"{--}"deconfigure" "\\"
    "in"{--}"favour" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"package"{--}"being"{--}"installed"{--}"but"{--}"failed"}} {1.4285714285 1.0} @Scale {{Times Slope} @Font version} "\\"
    removing {1.4285714285 1.0} @Scale {{Times Slope} @Font {"conflicting"{--}"package"}} {1.4285714285 1.0} @Scale {{Times Slope} @Font version}}}}}
//{0.2fe} The deconfigured packages are marked as requiring configuration, so
that if {0.7 1.0} @Scale {{Courier Bold} @Font {""{--}""{--}"install"}} is used they will be configured again if
possible.}
// @LVis listitem {To prepare for removal of the conflicting package, call:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"conflictor's"{--}"prerm"}} remove "in"{--}"favour" {1.4285714285 1.0} @Scale {{Times Slope} @Font package} {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} Error unwind:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"conflictor's"{--}"postinst"}} "abort"{--}"remove" "\\"
    "in"{--}"favour" {1.4285714285 1.0} @Scale {{Times Slope} @Font package} {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.programmer.lout.72" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.76" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.73" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.73" }
{@RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {If the package is being upgraded, call:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"preinst"}} upgrade {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {Otherwise, if the package had some configuration files from a previous
version installed (ie, it is in the `configuration files only' state):
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"preinst"}} install {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {Otherwise (ie, the package was completely purged):
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"preinst"}} install}}}}
//{0.2fe} Error unwind versions, respectively:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "abort"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}
{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "abort"{--}"install" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}
{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "abort"{--}"install"}}}}
//{0.2fe} }
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { {@Roman&&{num}}. }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.75" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.73" }
{@RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {If the package is being upgraded, call:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"preinst"}} upgrade {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {Otherwise, if the package had some configuration files from a previous
version installed (ie, it is in the `configuration files only' state):
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"preinst"}} install {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {Otherwise (ie, the package was completely purged):
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"preinst"}} install}}}}
//{0.2fe} Error unwind versions, respectively:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "abort"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}
{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "abort"{--}"install" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}
{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "abort"{--}"install"}}}}
//{0.2fe} }
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.programmer.lout.74" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.73" }
{@RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {If the package is being upgraded, call:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"preinst"}} upgrade {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {Otherwise, if the package had some configuration files from a previous
version installed (ie, it is in the `configuration files only' state):
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"preinst"}} install {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {Otherwise (ie, the package was completely purged):
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"preinst"}} install}}}}
//{0.2fe} Error unwind versions, respectively:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "abort"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}
{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "abort"{--}"install" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}
{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "abort"{--}"install"}}}}
//{0.2fe} }
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { {@Roman&&{num}}. }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.77" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.73" }
{@RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {If the package is being upgraded, call:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"preinst"}} upgrade {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {Otherwise, if the package had some configuration files from a previous
version installed (ie, it is in the `configuration files only' state):
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"preinst"}} install {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {Otherwise (ie, the package was completely purged):
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"preinst"}} install}}}}
//{0.2fe} Error unwind versions, respectively:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "abort"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}
{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "abort"{--}"install" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}
{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "abort"{--}"install"}}}}
//{0.2fe} }
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.programmer.lout.75" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.73" }
{@RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {If the package is being upgraded, call:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"preinst"}} upgrade {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {Otherwise, if the package had some configuration files from a previous
version installed (ie, it is in the `configuration files only' state):
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"preinst"}} install {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {Otherwise (ie, the package was completely purged):
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"preinst"}} install}}}}
//{0.2fe} Error unwind versions, respectively:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "abort"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}
{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "abort"{--}"install" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}
{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "abort"{--}"install"}}}}
//{0.2fe} }
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { {@Roman&&{num}}. }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.78" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.73" }
{@RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {If the package is being upgraded, call:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"preinst"}} upgrade {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {Otherwise, if the package had some configuration files from a previous
version installed (ie, it is in the `configuration files only' state):
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"preinst"}} install {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {Otherwise (ie, the package was completely purged):
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"preinst"}} install}}}}
//{0.2fe} Error unwind versions, respectively:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "abort"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}
{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "abort"{--}"install" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}
{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "abort"{--}"install"}}}}
//{0.2fe} }
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.programmer.lout.76" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
29}
{@PageMarker
   @Tag { "582.programmer.lout.29" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.44" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 4}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.79" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.77" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.77" }
{The new package's files are unpacked, overwriting any that may be on
the system already, for example any from the old version of the same
package or from another package (backups of the old files are left
around, and if anything goes wrong dpkg will attempt to put them back
as part of the error unwind).
//{@ParaGap} It is an error for a package to contains files which are on the system
in another package, unless {0.7 1.0} @Scale {{Courier Bold} @Font Replaces} is used (see
`{{0.7 1.0} @Scale {{Courier Bold} @Font Replaces}} "-" overwriting files and replacing packages', page {@PageOf {s-replaces}}{).} Currently the {0.7 1.0} @Scale {{Courier Bold} @Font {""{--}""{--}"force"{--}"overwrite"}} flag is
enabled, downgrading it to a warning, but this may not always be the
case.
//{@ParaGap} Packages which overwrite each other's files produce behaviour which
though deterministic is hard for the system administrator to
understand. It can easily lead to `missing' programs if, for example,
a package is installed which overwrites a file from another package,
and is then removed {again.}{@FootNote {Part of the problem is due to what
is arguably a bug in {{0.7 1.0} @Scale {{Courier Bold} @Font dpkg}}.}}}}
{@LVis x}
@LClos
{@FootNote
   @Tag { "2521.programmer.lout.16" }
{Part of the problem is due to what
is arguably a bug in {{0.7 1.0} @Scale {{Courier Bold} @Font dpkg}}.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 5}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.82" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.78" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.78" }
{@RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {If the package is being upgraded, call
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"postrm"}} upgrade {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {If this fails, {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} will attempt:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "failed"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} Error unwind, for both cases:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"preinst"}} "abort"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
//  & @LVis endlist
// 
//{0ve} 
//{@ParaGap} This is the point of no return "-" if {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} gets this far, it won't
back off past this point if an error occurs. This will leave the
package in a fairly bad state, which will require a successful
reinstallation to clear up, but it's when {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} starts doing
things that are irreversible.}}
{@LVis x}
@LClos
{@RawList
   style { {@Roman&&{num}}. }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.81" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.78" }
{@RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {If the package is being upgraded, call
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"postrm"}} upgrade {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {If this fails, {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} will attempt:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "failed"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} Error unwind, for both cases:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"preinst"}} "abort"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
//  & @LVis endlist
// 
//{0ve} 
//{@ParaGap} This is the point of no return "-" if {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} gets this far, it won't
back off past this point if an error occurs. This will leave the
package in a fairly bad state, which will require a successful
reinstallation to clear up, but it's when {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} starts doing
things that are irreversible.}}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.programmer.lout.79" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.78" }
{@RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {If the package is being upgraded, call
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"postrm"}} upgrade {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {If this fails, {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} will attempt:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "failed"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} Error unwind, for both cases:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"preinst"}} "abort"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
//  & @LVis endlist
// 
//{0ve} 
//{@ParaGap} This is the point of no return "-" if {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} gets this far, it won't
back off past this point if an error occurs. This will leave the
package in a fairly bad state, which will require a successful
reinstallation to clear up, but it's when {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} starts doing
things that are irreversible.}}
{@LVis x}
@LClos
{@RawList
   style { {@Roman&&{num}}. }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.83" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.78" }
{@RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {If the package is being upgraded, call
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"postrm"}} upgrade {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {If this fails, {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} will attempt:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"postrm"}} "failed"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"version"}}}}}}
//{0.2fe} Error unwind, for both cases:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"old"{--}"preinst"}} "abort"{--}"upgrade" {1.4285714285 1.0} @Scale {{Times Slope} @Font {"new"{--}"version"}}}}}}
//{0.2fe} }
//  & @LVis endlist
// 
//{0ve} 
//{@ParaGap} This is the point of no return "-" if {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} gets this far, it won't
back off past this point if an error occurs. This will leave the
package in a fairly bad state, which will require a successful
reinstallation to clear up, but it's when {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} starts doing
things that are irreversible.}}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.programmer.lout.80" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 6}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.84" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.81" }
{Any files which were in the old version of the package but not in the
new are removed.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 7}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.85" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.82" }
{The new file list replaces the old.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 8}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.86" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.83" }
{The new maintainer scripts replace the old.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 9}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.87" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.84" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.84" }
{Any packages all of whose files have been overwritten during the
installation, and which aren't required for dependencies, are considered
to have been removed. For each such package,
//{@ParaGap} @RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {{0.7 1.0} @Scale {{Courier Bold} @Font dpkg} calls:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"disappearer's"{--}"postrm"}} disappear "\\"
    {1.4285714285 1.0} @Scale {{Times Slope} @Font overwriter} {1.4285714285 1.0} @Scale {{Times Slope} @Font {"overwriter"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {The package's maintainer scripts are removed.}
// @LVis listitem {It is noted in the status database as being in a sane state, namely
not installed (any conffiles it may have are ignored, rather than
being removed by {{0.7 1.0} @Scale {{Courier Bold} @Font dpkg}}{).} Note that disappearing packages do not
have their prerm called, because {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} doesn't know in advance
that the package is going to vanish.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { {@Roman&&{num}}. }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.88" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.84" }
{Any packages all of whose files have been overwritten during the
installation, and which aren't required for dependencies, are considered
to have been removed. For each such package,
//{@ParaGap} @RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {{0.7 1.0} @Scale {{Courier Bold} @Font dpkg} calls:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"disappearer's"{--}"postrm"}} disappear "\\"
    {1.4285714285 1.0} @Scale {{Times Slope} @Font overwriter} {1.4285714285 1.0} @Scale {{Times Slope} @Font {"overwriter"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {The package's maintainer scripts are removed.}
// @LVis listitem {It is noted in the status database as being in a sane state, namely
not installed (any conffiles it may have are ignored, rather than
being removed by {{0.7 1.0} @Scale {{Courier Bold} @Font dpkg}}{).} Note that disappearing packages do not
have their prerm called, because {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} doesn't know in advance
that the package is going to vanish.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.programmer.lout.85" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.84" }
{Any packages all of whose files have been overwritten during the
installation, and which aren't required for dependencies, are considered
to have been removed. For each such package,
//{@ParaGap} @RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {{0.7 1.0} @Scale {{Courier Bold} @Font dpkg} calls:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"disappearer's"{--}"postrm"}} disappear "\\"
    {1.4285714285 1.0} @Scale {{Times Slope} @Font overwriter} {1.4285714285 1.0} @Scale {{Times Slope} @Font {"overwriter"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {The package's maintainer scripts are removed.}
// @LVis listitem {It is noted in the status database as being in a sane state, namely
not installed (any conffiles it may have are ignored, rather than
being removed by {{0.7 1.0} @Scale {{Courier Bold} @Font dpkg}}{).} Note that disappearing packages do not
have their prerm called, because {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} doesn't know in advance
that the package is going to vanish.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { {@Roman&&{num}}. }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.89" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.84" }
{Any packages all of whose files have been overwritten during the
installation, and which aren't required for dependencies, are considered
to have been removed. For each such package,
//{@ParaGap} @RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {{0.7 1.0} @Scale {{Courier Bold} @Font dpkg} calls:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"disappearer's"{--}"postrm"}} disappear "\\"
    {1.4285714285 1.0} @Scale {{Times Slope} @Font overwriter} {1.4285714285 1.0} @Scale {{Times Slope} @Font {"overwriter"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {The package's maintainer scripts are removed.}
// @LVis listitem {It is noted in the status database as being in a sane state, namely
not installed (any conffiles it may have are ignored, rather than
being removed by {{0.7 1.0} @Scale {{Courier Bold} @Font dpkg}}{).} Note that disappearing packages do not
have their prerm called, because {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} doesn't know in advance
that the package is going to vanish.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.programmer.lout.86" }
{The package's maintainer scripts are removed.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.84" }
{Any packages all of whose files have been overwritten during the
installation, and which aren't required for dependencies, are considered
to have been removed. For each such package,
//{@ParaGap} @RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {{0.7 1.0} @Scale {{Courier Bold} @Font dpkg} calls:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"disappearer's"{--}"postrm"}} disappear "\\"
    {1.4285714285 1.0} @Scale {{Times Slope} @Font overwriter} {1.4285714285 1.0} @Scale {{Times Slope} @Font {"overwriter"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {The package's maintainer scripts are removed.}
// @LVis listitem {It is noted in the status database as being in a sane state, namely
not installed (any conffiles it may have are ignored, rather than
being removed by {{0.7 1.0} @Scale {{Courier Bold} @Font dpkg}}{).} Note that disappearing packages do not
have their prerm called, because {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} doesn't know in advance
that the package is going to vanish.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@RawList
   style { {@Roman&&{num}}. }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.90" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.84" }
{Any packages all of whose files have been overwritten during the
installation, and which aren't required for dependencies, are considered
to have been removed. For each such package,
//{@ParaGap} @RawList
   style { {@Roman&&{num}}. }
// @LVis listitem {{0.7 1.0} @Scale {{Courier Bold} @Font dpkg} calls:
//{1.0vx} 
|{@DisplayIndent} @LVis @DispPlace
| @LVis @Disp {lines @Break {{0.7 1.0} @Scale {{Courier Bold} @Font {{1.4285714285 1.0} @Scale {{Times Slope} @Font {"disappearer's"{--}"postrm"}} disappear "\\"
    {1.4285714285 1.0} @Scale {{Times Slope} @Font overwriter} {1.4285714285 1.0} @Scale {{Times Slope} @Font {"overwriter"{--}"version"}}}}}}
//{0.2fe} }
// @LVis listitem {The package's maintainer scripts are removed.}
// @LVis listitem {It is noted in the status database as being in a sane state, namely
not installed (any conffiles it may have are ignored, rather than
being removed by {{0.7 1.0} @Scale {{Courier Bold} @Font dpkg}}{).} Note that disappearing packages do not
have their prerm called, because {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} doesn't know in advance
that the package is going to vanish.}
//  & @LVis endlist
// 
//{0ve} }}
{@LVis x}
@LClos
{@LVis listitem
   @Tag { "1655.programmer.lout.87" }
{It is noted in the status database as being in a sane state, namely
not installed (any conffiles it may have are ignored, rather than
being removed by {{0.7 1.0} @Scale {{Courier Bold} @Font dpkg}}{).} Note that disappearing packages do not
have their prerm called, because {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} doesn't know in advance
that the package is going to vanish.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.16"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.45" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.16"}
{@LVis @NumberMarker
   @Tag { "2521.programmer.lout.16" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
29}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
30}
{@PageMarker
   @Tag { "582.programmer.lout.30" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.46" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 10}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.91" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.88" }
{Any files in the package we're unpacking that are also listed in the
file lists of other packages are removed from those lists. (This will
lobotomise the file list of the `conflicting' package if there is one.)}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 11}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.92" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.89" }
{The backup files made during installation, above, are deleted.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 12}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.93" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.90" }
{The new package's status is now sane, and recorded as `unpacked'. Here
is another point of no return "-" if the conflicting package's removal
fails we do not unwind the rest of the installation; the conflicting
package is left in a "half-removed" limbo.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 13}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.94" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.91" }
{If there was a conflicting package we go and do the removal actions
(described below), starting with the removal of the conflicting
package's files (any that are also in the package being installed
have already been removed from the conflicting package's file list,
and so do not get removed now).}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.96" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.92" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.97" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.93" }
{The package's files are removed (except conffiles).}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.99" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.94" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 4}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.100" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.95" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 5}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.101" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.96" }
{The conffiles and any backup files ({{0.7 1.0} @Scale {{Courier Bold} @Font {{} ~ {}}}}"-files," {0.7 1.0} @Scale {{Courier Bold} @Font "#*#"} files,
{{0.7 1.0} @Scale {{Courier Bold} @Font %}}"-files," {{0.7 1.0} @Scale {{Courier Bold} @Font {".dpkg"{--}"{old,new,tmp}"}}}, etc.) are removed.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
31}
{@PageMarker
   @Tag { "582.programmer.lout.31" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.47" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 6}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.103" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.97" }
???}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { {num}. }}
{@LVis @MakeList 7}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.104" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.98" }
{The package's file list is removed.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
31}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
32}
{@PageMarker
   @Tag { "582.programmer.lout.32" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.48" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.105" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.99" }
{Those starting with a single space are part of a paragraph.
Successive lines of this form will be "word-wrapped" when displayed.
The leading space will usually be stripped off.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.106" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.100" }
{Those starting with two or more spaces. These will be displayed
verbatim. If the display cannot be panned horizontally the
displaying program will linewrap them `hard' (ie, without taking
account of word breaks). If it can they will be allowed to trail
off to the right. None, one or two initial spaces may be deleted,
but the number of spaces deleted from each line will be the same
(so that you can have indenting work correctly, for example).}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.107" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.101" }
{Those containing a single space followed by a single full stop
character. These are rendered as blank lines. This is the {Times Slope} @Font only
way to get a blank line "-" see below.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }}
{@LVis @MakeList 4}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.108" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.102" }
{Those containing a space, a full stop and some more characters. These
are for future expansion. Do not use them.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@FootNote
   @Tag { "2521.programmer.lout.17" }
{Version 0.93.23 or
later.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.17"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.49" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.17"}
{@LVis @NumberMarker
   @Tag { "2521.programmer.lout.17" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
33}
{@PageMarker
   @Tag { "582.programmer.lout.33" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.50" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
33}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
34}
{@PageMarker
   @Tag { "582.programmer.lout.34" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.51" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
35}
{@PageMarker
   @Tag { "582.programmer.lout.35" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.52" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
35}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
36}
{@PageMarker
   @Tag { "582.programmer.lout.36" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.53" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis @Disp ??}
{@LVis x}
@LClos
{@FootNote
   @Tag { "2521.programmer.lout.18" }
{Current versions
(1.2.4) of {0.7 1.0} @Scale {{Courier Bold} @Font dpkg} have a bug in this area which will cause some of
these problems to be ignored.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.18"}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.54" }
   count { @LVis @FootNoteNum @LVis tag }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterIncrement "2521.programmer.lout.18"}
{@LVis @NumberMarker
   @Tag { "2521.programmer.lout.18" }
   @Value { @LVis @FootNoteNumbers @LVis @Num {@LVis @FootNoteNum @LVis tag} }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
37}
{@PageMarker
   @Tag { "582.programmer.lout.37" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.55" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
37}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
38}
{@PageMarker
   @Tag { "582.programmer.lout.38" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.56" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
39}
{@PageMarker
   @Tag { "582.programmer.lout.39" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.57" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
39}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
40}
{@PageMarker
   @Tag { "582.programmer.lout.40" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.58" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
41}
{@PageMarker
   @Tag { "582.programmer.lout.41" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.59" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
41}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
42}
{@PageMarker
   @Tag { "582.programmer.lout.42" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.60" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
43}
{@PageMarker
   @Tag { "582.programmer.lout.43" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.61" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
43}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
44}
{@PageMarker
   @Tag { "582.programmer.lout.44" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.62" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
45}
{@PageMarker
   @Tag { "582.programmer.lout.45" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.63" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
45}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
46}
{@PageMarker
   @Tag { "582.programmer.lout.46" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.64" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
47}
{@PageMarker
   @Tag { "582.programmer.lout.47" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.65" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
47}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
48}
{@PageMarker
   @Tag { "582.programmer.lout.48" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.66" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
49}
{@PageMarker
   @Tag { "582.programmer.lout.49" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.67" }
   count { 0 }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 1}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.109" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.103" }
{Setup installation parameters.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 2}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.110" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.104" }
{Update list of available packages.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@RawList
   style { @Bullet }
   gap { 1.0vx }}
{@LVis @MakeList 3}
{@LVis @NumberMarker
   @Tag { "1306.programmer.lout.111" }
   @Value { @LVis style @LVis num }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LUse @OrdinaryLayout}
{@Text { @LInput }}
{@LVis listitem
   @Tag { "1655.programmer.lout.105" }
{Install.}}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @RunningPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
49}
{@LVis @RunningEvenPageList
   @ColumnNumber { 1 }
   @PageHeaders { Titles }
50}
{@PageMarker
   @Tag { "582.programmer.lout.50" }
   num { @LVis @PageNumbers @LVis @Num @LVis @PageNum }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{@LVis @FootNoteCounterMarker
   @Tag { "2495.programmer.lout.68" }
   count { 0 }}
@LClos
}

{@OptGall {1 52 47 28 42 45 48 47 42 42 46 43 51 38 46 45 46 57 33 45
47 44 46 50 59 35 32 42 54 42 43 42 22 35 20 41 41 46 41 42
35 33 35 15 25 23 44 44 28 50 24}}

{@LEnv
{@LUse @DocumentLayout}
{NonStart @Runner
   @Tag { "1954.programmer.lout.4" }}
@LClos
}

{@LEnv
{@LUse @DocumentLayout}
{NonStart @Runner
   @Tag { "1954.programmer.lout.2" }}
@LClos
}

