.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\"
.\" Updated by <alexm@hsys.msk.ru> to r1.2 of 822-date.1 from CVS
.\"
.\" Authors: Ian Jackson
.TH 822\-DATE 1 "14 августа 1996" "Проект Debian" "утилиты dpkg"
.SH НАЗВАНИЕ 
822\-date \- печатает дату и время в формате RFC822
.SH СИНТАКСИС
.B 822\-date
.SH ОПИСАНИЕ
.B 822\-date
показывает текущую дату и время в соответствии с форматом, описанным в RFC822,
используя числовое смещение часового пояса, согласно RFC1123.
.SH ПАРАМЕТРЫ
.B 822\-date
не использует аргументов или параметров.
.SH ОШИБКИ РЕАЛИЗАЦИИ
На самом деле эта функциональность должна находиться в программе
.BR date (1).
.SH "СМОТРИ ТАКЖЕ"
.I Standard for the Format of ARPA Internet Text Messages
(RFC822),
.br
.I Requirements for Internet Hosts -- Application and Support
(RFC1123) section 5.2.14,
.br
.BR date (1).
.SH АВТОР
.B 822\-date
и эту страницу руководства написал и передал в общественное достояние
Ian Jackson.
.SH ПЕРЕВОД
Юрий Козлов <y_kozlov@chat.ru>.
.\" dpkg-1.9.0
.\" 
.\" $Date: 2002/02/02 15:57:02 $

