.\"
.\" Updated by <alexm@hsys.msk.ru> to r1.2 of dpkg-checkbuilddeps.1 from CVS
.\"
.TH DPKG-CHECKBUILDDEPS 1 "Февраль 2001" "Проект Debian" "утилиты dpkg"
.SH НАЗВАНИЕ
dpkg-checkbuilddeps -- проверяет зависимости и конфликты при сборке
.SH СИНТАКСИС
\fBdpkg-checkbuilddeps\fR -B [\fIфайл control\fR]
.SH ОПИСАНИЕ
Эта программа проверяет установленные в системе пакеты на предмет сборочных
зависимостей и сборочных конфликтов, описанных в файле control.  Если
какие-то из этих зависимостей или конфликтов не удовлетворены,
то об этом сообщается и происходит выход с ненулевым кодом возврата.
.P
По умолчанию читается \fBdebian/control\fR, но в командной строке можно
задать другое имя управляющего файла.
.SH ПАРАМЕТРЫ
.TP
.I -B
Игнорировать строки Build-Depends-Indep.  Используется, если пакеты,
независящие от архитектуры, не будут собираться.
.SH АВТОР
Copyright 2001 Joey Hess
.UR mailto:joeyh@debian.org
<joeyh@debian.org>
.UE
.sp
Это свободная программа; см. Универсальную Общественную Лицензии GNU версии\~2 или
более позднюю, где изложены условия распространения.  НИКАКИХ гарантий.
.SH ПЕРЕВОД
Юрий Козлов <y_kozlov@chat.ru>.
.\" dpkg-1.9.0
.\" 
.\" $Date: 2002/02/02 15:57:02 $
.\" Домашняя страница				http://www.chat.ru/~y_kozlov/
