../dpkg.cfg etc/dpkg

etc/dpkg/dpkg.cfg.d
etc/alternatives
sbin/start-stop-daemon
usr/bin/dpkg
usr/bin/dpkg-deb
usr/bin/dpkg-divert
usr/bin/dpkg-maintscript-helper
usr/bin/dpkg-query
usr/bin/dpkg-split
usr/bin/dpkg-statoverride
usr/bin/dpkg-trigger
usr/bin/update-alternatives
usr/share/dpkg/*table
usr/share/locale/*/LC_MESSAGES/dpkg.mo
var/lib/dpkg/alternatives
var/lib/dpkg/info
var/lib/dpkg/parts
var/lib/dpkg/updates
