../shlibs.default etc/dpkg
../shlibs.override etc/dpkg

usr/bin/dpkg-architecture
usr/bin/dpkg-buildflags
usr/bin/dpkg-buildpackage
usr/bin/dpkg-checkbuilddeps
usr/bin/dpkg-distaddfile
usr/bin/dpkg-genbuildinfo
usr/bin/dpkg-genchanges
usr/bin/dpkg-gencontrol
usr/bin/dpkg-gensymbols
usr/bin/dpkg-mergechangelogs
usr/bin/dpkg-name
usr/bin/dpkg-parsechangelog
usr/bin/dpkg-scanpackages
usr/bin/dpkg-scansources
usr/bin/dpkg-shlibdeps
usr/bin/dpkg-source
usr/bin/dpkg-vendor
usr/share/dpkg/*.mk
