#!/bin/sh
set -e

FLAVOR=$1
PACKAGE=dpkg-dev

if [ ${FLAVOR} != emacs ]; then
  echo remove/${PACKAGE}: Purging byte-compiled files for ${FLAVOR}
  rm -rf /usr/share/${FLAVOR}/site-lisp/${PACKAGE}
  rm -f /etc/${FLAVOR}/site-start.d/50dpkg-dev.el
fi
