#!/bin/sh
self="$(basename "$0")"
from="$(dirname "$0")"
case "$1" in
n=source)
  echo "$self: source-opts=$DPKG_BUILDPACKAGE_HOOK_SOURCE_OPTIONS"
  ;;
n=build)
  echo "$self: build-target=$DPKG_BUILDPACKAGE_HOOK_BUILD_TARGET"
  ;;
n=binary)
  echo "$self: binary-target=$DPKG_BUILDPACKAGE_HOOK_BINARY_TARGET"
  ;;
n=buildinfo)
  echo "$self: buildinfo-opts=$DPKG_BUILDPACKAGE_HOOK_BUILDINFO_OPTIONS" \
    | perl -p -E "s{\Q$from\E}{<ROOT>}g"
  ;;
n=changes)
  echo "$self: changes-opts=$DPKG_BUILDPACKAGE_HOOK_CHANGES_OPTIONS"
  ;;
n=check)
  echo "$self: check-opts=$DPKG_BUILDPACKAGE_HOOK_CHECK_OPTIONS"
  ;;
esac
echo "$self: $*"
