.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.TH START\-STOP\-DAEMON 8 "15th March 1997" "Debian Project" "Debian GNU/Linux"
.SH NAME
start\-stop\-daemon \- start and stop system daemon programs
.SH SYNOPSIS
.B start-stop-daemon
.BR -S|--start
.IR "options ... -- arguments ..."
.HP
.B start-stop-daemon
.BR -K|--stop
.IR "options ..."
.HP
.B start-stop-daemon
.BR -H|--help
.HP
.B start-stop-daemon
.BR -V|--version
.SH DESCRIPTION
.B start\-stop\-daemon
is used to control the creation and termination of system-level processes.
Using the
.BR --exec
,
.BR --pidfile
,
.BR --user
, and
.BR --name
options, 
.B start\-stop\-daemon
can be configured to find existing instances of a running process.

With
.BR --start
,
.B start\-stop\-daemon
checks for the existence of a specified process.
If such a process exists,
.B start\-stop\-daemon
does nothing, and exits with error status 1 (0 if
.BR --oknodo
is specified).  
If such a process does not exist, it starts an
instance, using either the executable specified by
.BR --exec
, (or, if specified, by
.BR --startas
).
Any arguments given after
.BR --
on the command line are passed unmodified to the program being
started.

With 
.BR --stop
,
.B start\-stop\-daemon
also checks for the existence of a specified process.
If such a process exists,
.B start\-stop\-daemon
sends it the signal specified by
.BR --signal
, and exits with error status 0.
If such a process does not exist,
.B start\-stop\-daemon
exits with error status 1
(0 if 
.BR --oknodo
is specified).  

.SH OPTIONS

.TP
.I -x|--exec executable
Check for processes that are instances of this executable (according to 
.B /proc/
.I pid
.B /exe 
).
.TP
.I -p|--pidfile pid-file
Check for processes whose process-id is specified in 
.I pid-file.
.TP
.I -u|--user username|uid
Check for processes owned by the user specified by
.I username 
or
.I uid.
.TP
.I -n|--name process-name
Check for processes with the name
.I process-name
(according to
.B /proc/
.I pid
.B /stat 
).
.TP
.I -s|--signal signal
With
.BR --stop
, specifies the signal to send to processes being stopped (default 15).
.TP
.I -a|--startas pathname
With 
.B --start
, start the process specified by 
.I pathname.
If not specified, defaults to the argument given to
.B --exec.
.TP
.I -t|--test
Print actions that would be taken and set appropriate return value,
but take no action.
.TP
.I -o|--oknodo
Return exit status 0 instead of 1 if no actions are (would be) taken.
.TP
.I -q|--quiet
Do not print informational messages; only display error messages.
.TP
.I -c|--chuid
Change to this username/uid before starting the process. You can also
specify a group by appending a ':', then the group or gid in the same way
as you would for the `chown' command (user:group). When using this option
you must realize that the primary and suplimental groups are set as well,
even if the `group' options is not specified. The group option is only for
groups that the user isn't normally a member of (like adding per/process
group membership for generic users like `nobody').
.TP
.I -r|--chroot root
Chdir and chroot to
.B root
before starting the process. Please note that the pidfile is also written
after the chroot.
.TP
.I -b|--background
Typically used with programs that don't detach on their own. This option
will force
.B start-stop-daemon
to fork before starting the process, and force it into the background.
.B WARNING:
start-stop-daemon
cannot check the exit status if the process fails to execute for
.B any
reason. This is a last resort, and is only meant for programs that either
make no sense forking on their own, or where it's not feasible to add the
code for it to do this itself.
.TP
.I -m|--make-pidfile
Used when starting a program that does not create its own pid file. This
option will make
.B start-stop-daemon
create the file referenced with
.B --pidfile
and place the pid into it just before executing the process. Note, it will
not be removed when stopping the program.
.B NOTE:
This feature may not work in all cases. Most notably when the program
being executed forks from it's main process. Because of this it is usually
only useful when combined with the
.B --background
option.
.TP
.I -v|--verbose
Print verbose informational messages.
.TP
.I -H|--help
Print help information; then exit.
.TP
.I -V|--version
Print version information; then exit.

.SH AUTHORS
Ian Jackson <ijackson@gnu.ai.mit.edu>

Marek Michalkiewicz <marekm@i17linuxb.ists.pwr.wroc.pl>

Manual page by Klee Dienes <klee@mit.edu>.
