.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\" Authors: Ian Jackson
.TH 822\-DATE 1 "14th August 1996" "Debian Project" "dpkg utilities"
.SH NAME 
822\-date \- Print date and time in RFC822 format
.SH SYNOPSIS
.B 822\-date
.SH DESCRIPTION
.B 822\-date
displays the current date and time in the format described in RFC822,
using a numeric timezone offset as recommended in RFC1123.
.SH OPTIONS
.B 822\-date
does not take any arguments or options.
.SH BUGS
This facility really ought to be part of
.BR date (1),
.SH SEE ALSO
.I Standard for the Format of ARPA Internet Text Messages
(RFC822),
.br
.I Requirements for Internet Hosts -- Application and Support
(RFC1123) section 5.2.14,
.br
.BR date (1).
.SH AUTHOR
.B 822\-date
and this manpage were written by Ian Jackson.  They are hereby placed
by him into the public domain.
