.\" This manpage is copyright (C) 1996 Michael Shields <shields@crosslink.net>.
.\" 
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with dpkg; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.TH DPKG\-SCANPACKAGES 1 "1996-07-08" "Debian project" "dpkg utilities"
.SH NAME
dpkg\-scanpackages - create Packages files
.
.SH SYNOPSIS
.B dpkg\-scanpackages
.RI [ \-u ]
.RI [ \-a<arch> ]
.I binarydir
.I overridefile
.RI [ pathprefix ]
.B >
.I Packages
.
.SH DESCRIPTION
.B dpkg\-scanpackages
sorts through a tree of Debian binary packages and creates a Packages
file, used by
.BR dselect (1),
etc, to tell the user what packages are available for installation.  These
Packages files are the same as those found on Debian archive sites
and CD-ROMs.  You might use
.B dpkg\-scanpackages
yourself if making a directory of local packages to install on a cluster
of machines.
.PP
.I binarydir
is the name of the binary tree to process (for example,
.BR contrib/binary\-i386 ).
It is best to make this relative to the root of the Debian archive,
because every Filename field in the new Packages file will start with
this string.
.PP
.I overridefile
is the name of a file to read which contains information about how the
package fits into the distribution; see below.
.PP
.I pathprefix
is an optional string to be prepended to the Filename fields.
.PP
If
.I \-u
is specified, then scan for *.udeb, instead of *.deb.
.PP
When \-a\fI<arch>\fP is specified, then instead of scanning for all debs,
a pattern consisting of *_all.deb and *_arch.deb is used.
.
.SH THE OVERRIDE FILE
While most information about a package can be found in the control file,
some must be filled in by the distribution czars rather than by the
maintainer, because they relate to the arrangement of files for release
rather than the actual dependencies and description of the package.
This information is found in the override file.
.PP
The override file has a simple whitespace-delimited format.  Comments are
allowed (denoted with a
.BR # ).
.PP
.in +5
.I package
.I priority
.I section
.RI [ maintainerinfo ]
.in -5
.PP
.I package
is the name of the package.  Entries in the override file for packages
not found in the binary tree are ignored.
.PP
.I priority
and
.I section
place the package within the release tree; these ought not to be found
in the control file.  If the package is found in a subdirectory of
.IR binarydir ,
that will be checked against
.IR section .
.PP
.IR maintainerinfo ,
if present, can be either the name of a maintainer for an unconditional
override, or else
.I oldmaintainer
.B =>
.I newmaintainer
to perform a substitution.
.PP
The override files used to make the official Packages lists may be found
in the
.I indices
directory on any Debian mirror.
.
.SH DIAGNOSTICS
.B dpkg\-scanpackages
outputs the usual self-explanatory errors.  It also warns about packages
that are in the wrong subdirectory, are duplicated, have a Filename
field in their control file, are missing from the override file, or have
maintainer substitutions which do not take effect.
.
.SH SEE ALSO
.BR dpkg (1),
.BR dselect (1),
.BR dpkg\-scansources (1).
