.TH DPKG.CFG 5 "February 2002" "Debian Project" "dpkg suite"
.SH NAME
dpkg.cfg \- dpkg configuration file
.SH DESCRIPTION
This file contains default options for dpkg. Each line contains a
single option which is exactly the same as a normal commandline
option for dpkg except for the leading dashes which are not used
here. Comments are allowed by starting a line with a hash sign
("\fB#\fR").
.SH FILES
.I /etc/dpkg/dpkg.cfg
~/.dpkg.cfg
.SH AUTHOR
See \fB/usr/share/doc/dpkg/THANKS\fP for the list of people who have
contributed to \fBdpkg\fP .
.SH SEE ALSO
.BR dpkg (1)
