.TH DPKG\-CHECKBUILDDEPS 1 "February 2001" "Debian project" "dpkg utililties"
.SH NAME
dpkg\-checkbuilddeps - check build dependencies and conflicts
.SH SYNOPSIS
\fBdpkg\-checkbuilddeps\fR \-B [\fIcontrol-file\fR]
.SH DESCRIPTION
This program checks the installed packages in the system against the build
dependencies and build conflicts listed in the control file.  If any are
not met, it displays them and exits with a nonzero return code.
.P
By default, \fBdebian/control\fR is read, but an alternate control filename
may be specified on the command line.
.SH OPTIONS
.TP
.I \-B
Ignore Build-Depends-Indep lines. Use when no arch-indep packages will be
built.
.SH AUTHOR
Copyright 2001 Joey Hess
.UR mailto:joeyh@debian.org
<joeyh@debian.org>
.UE
.sp
This is free software; see the GNU General Public Licence version 2 or
later for copying conditions.  There is NO warranty.
