.TH DSELECT.CFG 5 "February 2002" "Debian Project" "dpkg suite"
.SH NAME
dselect.cfg \- dselect configuration file
.SH DESCRIPTION
This file contains default options for dselect. Each line contains a
single option which is exactly the same as a normal commandline
option for dselect except for the leading dashes which are not used
here. Comments are allowed by starting a line with a hash sign
("\fB#\fR").
.SH FILES
.I /etc/dpkg/dselect.cfg
~/.dselect.cfg
.SH AUTHOR
See \fB/usr/share/doc/dpkg/THANKS\fP for the list of people who have
contributed to \fBdselect\fP .
.SH SEE ALSO
.BR dselect (1)
