.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.TH DSELECT 8 "29th November 1995" "Debian Project" "Debian GNU/Linux"
.SH NAME
dselect \- a user tool to manage Debian GNU/Linux packages

.SH SYNOPSIS
.B dselect
[options]
.br
.B dselect
[options] action ...

.SH DESCRIPTION
.B dselect
is the primary user interface for installing, removing and managing
Debian GNU/Linux packages. It is an front-end to
.B dpkg(8).
Normally
.B dselect
is invoked without parameters, but some commandline parameters are still
available.

The usage of
.B dselect
is pretty self-explanatory, and also an internal help-system is
included, which describes the keystrokes and some general concepts.
.I Read the help.

.SS ACTIONS
.TP
.B access, update, select, install, config, remove
These actions automatically selects corresponding commands from the main
menu, without even showing the main menu to you.
.TP
.B quit
Do nothing but quit.
.TP
.B menu
Displays the default menu. This is equivalent to starting
.B dselect
with no parameters.

.SS OPTIONS
.TP
.B --admindir <directory>
Changes the directory where datafiles are located. This defaults to
.I /var/lib/dpkg.
Note, that these files are just some internal datafiles, actual Debian
packages doesn't have to be located here.
.TP
.B --debug <file> | -D<file>
Turn on debugging. Debugging information is sent to
.I <file>.
.TP
.B --help
Print a brief help text.
.TP
.B --licence
Print the licence of
.B dselect.
.TP
.B --version
Print version information.

.SH BUGS
This manpage doesn't document the options quite correctly, and has
formatting inconsistent with other manpages.

The
.B dselect
package selection interface is confusing or even alarming to the new
user.

There is no easy way automatically to download and install packages
via anonymous FTP.

.SH SEE ALSO
.B deb(5)
,
.B dpkg-deb(8)
,
.B dpkg(8)
and
.B deb-control(5)

.SH AUTHOR
.B dselect
was written by Ian Jackson (ijackson@gnu.ai.mit.edu).
This manual page is by Juho Vuori (javuori@cc.helsinki.fi).
