.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.TH DSELECT 8 "January 2000" "Debian Project" "Debian GNU/Linux"
.SH NAME
dselect \- console Debian package handling frontend
.SH SYNOPSIS
.B dselect
[--admindir <directory>] [--help] [--version] [--licence | --license]
[--expert] [--debug <file> | -D <file>] [\fI<action>\fP]
.SH DESCRIPTION
.B dselect
is the primary user interface for installing, removing and managing
Debian GNU/Linux packages. It is an front-end to
.B dpkg(8).
Normally
.B dselect
is invoked without parameters, but some commandline parameters are still
available.
.PP
The usage of
.B dselect
is pretty self-explanatory, and an internal help-system is included,
which describes the keystrokes and some general concepts.
.I Read the help.
.SS ACTIONS
.TP
.B Access
Chooses an access `method' to use to find package repository. By default,
there exist several methods such as "floppy", "harddisk", "cdrom", but
other packages you install can provide additional methods, e.g. "apt"
or "multi_cd" etc.
.TP
.B Update
Updates list of packages available to dpkg/dselect with data from the
chosen repository Packages file(s).
.TP
.B Select
Selects individual packages to install.
.TP
.B Install
Installs selected packages.
.TP
.B Config
Configures any previously not configured packages.
.TP
.B Remove
Removes or purges deselected packages.
.TP
.B Quit
Exit dselect (successfully).
.SH OPTIONS
.TP
.B --admindir <directory>
Changes the directory where the dpkg `status', `available' and similar
files are located. This defaults to
.I /var/lib/dpkg
and normally there shouldn't be any need to change it.
.TP
.B --debug <file> | -D<file>
Turn on debugging. Debugging information is sent to
.I <file>.
.TP
.B --expert
Turns on expert mode, i.e. doesn't display possibly annoying help messages.
.TP
.B --help
Print a brief help text and exit successfully.
.TP
.B --licence | --license
Displays the dselect copyright and license information and exits successfully.
.TP
.B --version
Print version information and exit successfully.
.SH BUGS
The
.B dselect
package selection interface is confusing or even alarming to a new user.
.sp
.B dselect
doesn't handle Recommends: field very well, and doesn't understand
Replaces: at all.
.sp
There is no easy way to automatically download and install packages
via anonymous FTP with default access methods (APT does this).
.SH SEE ALSO
.BR dpkg (8),
.BR deb (5).
.SH AUTHORS
.B dselect
was written by Ian Jackson (ijackson@gnu.ai.mit.edu). Full list of
contributors may be found in `dselect --license'.
.br
This manual page was written by Juho Vuori <javuori@cc.helsinki.fi>
and updated by Josip Rodin.
