.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\" Authors: Ian Jackson
.\" Translation of CVS revision 1.2
.TH 822\-DATE 1 "14 augusti 1996" "Debianprojektet" "dpkg-verktyg"
.SH NAMN
822\-date \- Skriv datum och tid i RFC822-format
.SH SYNOPS
.B 822\-date
.SH BESKRIVNING
.B 822\-date
visar aktuellt datum och tid i det format som beskrivs av RFC822, med en
numerisk tidszonsförskjutning enligt rekommendationen i RFC1123.
.SH FLAGGOR
.B 822\-date
tar inga flaggor eller parametrar.
.SH PROGRAMFEL
Denna funktion borde finnas i
.BR date (1).
.SH SE ÄVEN
.I Standard for the Format of ARPA Internet Text Messages
(RFC822),
.br
.I Requirements for Internet Hosts -- Application and Support
(RFC1123) section 5.2.14,
.br
.BR date (1).
.SH FÖRFATTARE
.B 822\-date
och denna manualsida skrevs av Ian Jackson.
De är härmed av honom släppta som allmängods (public domain).

Denna manualsida översattes av Peter Karlsson, och även denna översättning
är att anse som allmängods.
