#!/bin/sh
set -e

case "$1" in
  configure)
    if [ -z "$2" ]; then
       echo "FAIL: upgrading and no previous version passed to configure" 2>&1
       exit 1
    else
       echo "PASS: upgrading from version '$2'"
    fi
  ;;
esac

exit 0
