\input texinfo @c -*-texinfo-*-
@c %**start of header
@setfilename dpkg.info
@settitle The @code{dpkg} Package Maintenance System
@c %**end of header

@ifinfo
@format
START-INFO-DIR-ENTRY
* dpkg: (dpkg).          The @code{dpkg} package maintenance system.
END-INFO-DIR-ENTRY
@end format
@end ifinfo

@setchapternewpage off

@ifinfo
This file documents the @code{dpkg} package maintenance system.

Copyright (C) 1994 Ian A. Murdock

Permission is granted to make and distribute verbatim copies of this
document provided the copyright notice and this permission notice are
preserved on all copies.

@ignore
Permission is granted to process this file through TeX and print the
results, provided the printed document carries a copying permission
notice identical to this one, except for the removal of this paragraph
(this paragraph not being relevant to the printed manual).
@end ignore

Permission is granted to copy and distribute modified versions of this
document under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this document
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by The Debian Linux Association.
@end ifinfo

@titlepage
@title The @code{dpkg} Package Maintenance System
@author Ian A. Murdock
@page

@vskip 0pt plus 1filll
Copyright @copyright{} 1994 Ian A. Murdock

Permission is granted to make and distribute verbatim copies of this
document provided the copyright notice and this permission notice are
preserved on all copies.

Permission is granted to copy and distribute modified versions of this
document under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this document
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by The Debian Linux Association.
@end titlepage

@node Top, Overview, (dir), (dir)

@top Introduction
@menu
* Overview::            An overview of the @code{dpkg} package
                        maintenance system.
* Installation::        How to install a package with @code{dpkg}.
* Removal::             How to remove a package with @code{dpkg}.
* Information::         How to obtain information about both
                        installed and not-yet-installed packages.
* Extension::           How to extend @code{dpkg} to support new
                        package formats.
* Guidelines::          Guidelines for creating and maintaining
                        packages for Debian GNU/Linux.
@end menu

@node Overview
@chapter Overview

@node Installation
@chapter Package Installation

@node Removal
@chapter Package Removal

@node Information
@chapter Package Information

@node Guidelines
@chapter Debian GNU/Linux Guidelines

@node Extension
@chapter How to Extend @code{dpkg} to Support New Package Formats

@bye
