.\" Translation of CVS revision 1.1
.TH DPKG.CFG 5 "Februari 2002" "Debianprojektet" "dpkg-sviten"
.SH NAMN
dpkg.cfg \- inställningsfil för dpkg
.SH BESKRIVNING
Denna fil innehåller förvalda inställningar för dpkg.
Varje rad består av en ensam flagga som är exakt densamma som en normal
kommandoradsflagga för dpkg, förutom de inledande bindestrecken vilka
inte används här.
Kommentarer är tillåtna genom att inleda en rad med nummertecken
("\fB#\fR").
.SH FILER
.I /etc/dpkg/dpkg.cfg
~/.dpkg.cfg
.SH FÖRFATTARE
Se \fB/usr/share/doc/dpkg/THANKS\fP för listan över personer som har
bidragit till \fBdpkg\fP .
.SH SE ÄVEN
.BR dpkg (8)
