.\" Translation of CVS revision 1.2
.TH DSELECT.CFG 5 "Februari 2002" "Debianprojektet" "dpkg-sviten"
.SH NAMN
dselect.cfg \- inställningsfil för dselect
.SH BESKRIVNING
Denna fil innehåller förvalda inställningar för dselect.
Varje rad består av en ensam flagga som är exakt densamma som en normal
kommandoradsflagga för dselect, förutom de inledande bindestrecken vilka
inte används här.
Kommentarer är tillåtna genom att inleda en rad med nummertecken
("\fB#\fR").
.SH FILER
.I /etc/dpkg/dselect.cfg
~/.dselect.cfg
.SH FÖRFATTARE
Se \fB/usr/share/doc/dpkg/THANKS\fP för listan över personer som har
bidragit till \fBdselect\fP .
.SH SE ÄVEN
.BR dselect (8)
