name: NetBSD test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test dpkg on NetBSD
    steps:
    - uses: actions/checkout@v4
    - name: Test in NetBSD
      id: test
      uses: vmactions/netbsd-vm@v1
      with:
        usesh: true
        copyback: false
        prepare: |
          /usr/sbin/pkg_add pkgconf libtool autoconf automake gettext gtar gsed gcc13 patch gmake

        run: |
          ./.github/actions/ci-configure
          ./.github/actions/ci-test
