#!/bin/sh

case "$1" in
    remove)
	exit 1
	;;
    purge|upgrade|failed-upgrade|disappear|abort-install|abort-upgrade)
	;;
    *)
	echo "$0 called with unknown argument '$1'" 1>&2
	exit 1
	;;
esac

exit 0
